# Generated by Django 6.0.5 on 2026-09-22 12:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0006_wholesalefunnelevent'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentAttempt',
            fields=[
                ('inv_id', models.AutoField(primary_key=True, serialize=False, verbose_name='InvId')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Сумма снимка')),
                ('currency', models.CharField(default='KZT', max_length=3, verbose_name='Валюта')),
                ('mode', models.CharField(db_index=True, default='test', max_length=8, verbose_name='Режим')),
                ('hash_algo', models.CharField(default='sha256', max_length=16, verbose_name='Алгоритм подписи')),
                ('merchant_login', models.CharField(max_length=64, verbose_name='MerchantLogin')),
                ('seller_profile_id', models.PositiveIntegerField(verbose_name='ID продавца (снимок)')),
                ('status', models.CharField(choices=[('created', 'Создана'), ('confirmed', 'Подтверждена Result URL')], db_index=True, default='created', max_length=16, verbose_name='Статус попытки')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создана')),
                ('confirmed_at', models.DateTimeField(blank=True, null=True, verbose_name='Подтверждена Result URL')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='robokassa_payment_attempts', to=settings.AUTH_USER_MODEL, verbose_name='Создал')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payment_attempts', to='orders.order', verbose_name='Заказ')),
            ],
            options={
                'verbose_name': 'Попытка оплаты Robokassa',
                'verbose_name_plural': 'Попытки оплаты Robokassa',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['order', 'status', 'created_at'], name='pay_attempt_order_st_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('amount__gt', 0)), name='payments_attempt_amount_positive'), models.CheckConstraint(condition=models.Q(('currency', 'KZT')), name='payments_attempt_currency_kzt'), models.CheckConstraint(condition=models.Q(('mode', 'test')), name='payments_attempt_mode_test'), models.CheckConstraint(condition=models.Q(('hash_algo', 'sha256')), name='payments_attempt_algo_sha256'), models.CheckConstraint(condition=models.Q(('inv_id__gte', 1), ('inv_id__lte', 2147483647)), name='payments_attempt_invid_range')],
            },
        ),
    ]
