# Generated by Django 6.0.4 on 2026-05-11 09:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_requests', '0002_servicerequest_district_serviceseller_address_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceBroadcastSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mode', models.CharField(choices=[('off', 'OFF — рассылка выключена'), ('test', 'TEST — только тестовые исполнители'), ('live', 'LIVE — боевая рассылка')], default='off', max_length=10, verbose_name='Режим рассылки исполнителям')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
            ],
            options={
                'verbose_name': 'Broadcast Control исполнителей',
                'verbose_name_plural': 'Broadcast Control исполнителей',
            },
        ),
        migrations.AddField(
            model_name='serviceseller',
            name='dispatch_priority',
            field=models.PositiveIntegerField(default=1000, help_text='Чем меньше число, тем раньше исполнитель получает заявку.', verbose_name='Приоритет рассылки'),
        ),
        migrations.AddField(
            model_name='serviceseller',
            name='is_paused',
            field=models.BooleanField(default=False, help_text='Если включено, исполнитель временно не получает заявки.', verbose_name='Пауза'),
        ),
        migrations.AddField(
            model_name='serviceseller',
            name='is_test_seller',
            field=models.BooleanField(default=False, help_text='Используется только в TEST-режиме рассылки.', verbose_name='Тестовый исполнитель'),
        ),
        migrations.AddField(
            model_name='serviceseller',
            name='receive_requests',
            field=models.BooleanField(default=True, help_text='Участвует в LIVE-рассылке заявок исполнителям.', verbose_name='Получает заявки'),
        ),
        migrations.AlterField(
            model_name='servicematch',
            name='status',
            field=models.CharField(choices=[('new', 'Новая'), ('sent', 'Отправлена'), ('viewed', 'Просмотрена'), ('in_work', 'В работе'), ('done', 'Завершена')], default='new', max_length=20),
        ),
        migrations.CreateModel(
            name='ServiceWhatsAppMessageLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=30)),
                ('message_type', models.CharField(choices=[('seller_request', 'Заявка исполнителю'), ('buyer_notice', 'Уведомление клиенту'), ('manual', 'Ручная отправка')], default='seller_request', max_length=30)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('sent', 'Sent'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('meta_message_id', models.CharField(blank=True, max_length=255)),
                ('error_text', models.TextField(blank=True)),
                ('response_json', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('request', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='wa_logs', to='service_requests.servicerequest')),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wa_logs', to='service_requests.serviceseller')),
            ],
            options={
                'verbose_name': 'WhatsApp лог исполнителя',
                'verbose_name_plural': 'WhatsApp логи исполнителей',
                'ordering': ['-created_at'],
            },
        ),
    ]
