# Generated by Django 6.0.4 on 2026-05-17 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_requests', '0004_create_service_whatsapp_log_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviceseller',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='serviceseller',
            name='instagram',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='serviceseller',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='service_sellers/logos/'),
        ),
        migrations.AddField(
            model_name='serviceseller',
            name='website',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='serviceseller',
            name='working_hours',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
