# Generated by Django 6.0.5 on 2026-06-26 05:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service_requests', '0006_hash_service_seller_passwords'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='service',
            options={'verbose_name': 'Услуга', 'verbose_name_plural': 'Услуги'},
        ),
        migrations.AlterModelOptions(
            name='servicebroadcastsettings',
            options={'verbose_name': 'Управление рассылкой', 'verbose_name_plural': 'Управление рассылкой'},
        ),
        migrations.AlterModelOptions(
            name='servicematch',
            options={'verbose_name': 'Назначение исполнителю', 'verbose_name_plural': 'Назначения исполнителям'},
        ),
        migrations.AlterModelOptions(
            name='servicerequest',
            options={'verbose_name': 'Заявка клиента', 'verbose_name_plural': 'Заявки клиентов'},
        ),
        migrations.AlterModelOptions(
            name='serviceseller',
            options={'verbose_name': 'Исполнитель', 'verbose_name_plural': 'Исполнители'},
        ),
    ]
