# Generated by Django 6.0.5 on 2026-10-07 04:19

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_requests', '0008_service_security_foundation'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceRequestDispatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position_number', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('queued', 'В очереди'), ('processing', 'Отправляется'), ('sent', 'Отправлено'), ('failed', 'Ошибка'), ('skipped', 'Пропущено')], db_index=True, default='queued', max_length=20)),
                ('attempts_count', models.PositiveIntegerField(default=0)),
                ('next_attempt_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('last_attempt_at', models.DateTimeField(blank=True, null=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('provider_message_id', models.CharField(blank=True, max_length=255)),
                ('last_error', models.TextField(blank=True)),
                ('skip_reason', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dispatches', to='service_requests.servicerequest')),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='request_dispatches', to='service_requests.serviceseller')),
            ],
            options={
                'verbose_name': 'Очередь WhatsApp заявки',
                'verbose_name_plural': 'Очередь WhatsApp заявок',
                'indexes': [models.Index(fields=['status', 'next_attempt_at'], name='sr_dispatch_due_idx'), models.Index(fields=['request', 'position_number'], name='sr_dispatch_pos_idx')],
                'constraints': [models.UniqueConstraint(fields=('request', 'seller'), name='uniq_service_request_dispatch_seller')],
            },
        ),
    ]
