# Generated by Django 6.0.4 on 2026-04-20 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='brand',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='carmodel',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='brand',
            name='transport_type',
            field=models.CharField(choices=[('car', 'Легковые'), ('truck', 'Грузовые')], default='car', max_length=10),
        ),
        migrations.AddField(
            model_name='carmodel',
            name='transport_type',
            field=models.CharField(choices=[('car', 'Легковые'), ('truck', 'Грузовые')], default='car', max_length=10),
        ),
        migrations.AlterUniqueTogether(
            name='brand',
            unique_together={('country', 'name', 'transport_type')},
        ),
        migrations.AlterUniqueTogether(
            name='carmodel',
            unique_together={('brand', 'name', 'transport_type')},
        ),
    ]
