# Generated by Django 6.0.4 on 2026-04-21 08:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_brand_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='seller',
            name='brand_fk',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sellers', to='core.brand', verbose_name='Марка'),
        ),
        migrations.AddField(
            model_name='seller',
            name='country_fk',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sellers', to='core.country', verbose_name='Страна'),
        ),
        migrations.AddField(
            model_name='seller',
            name='model_fk',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sellers', to='core.carmodel', verbose_name='Модель'),
        ),
    ]
