# Generated by Django 6.0.4 on 2026-04-22 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_seller_brand_fk_seller_country_fk_seller_model_fk'),
    ]

    operations = [
        migrations.AddField(
            model_name='seller',
            name='all_brands',
            field=models.BooleanField(default=False, verbose_name='Все марки'),
        ),
        migrations.AddField(
            model_name='seller',
            name='all_categories',
            field=models.BooleanField(default=False, verbose_name='Все категории'),
        ),
        migrations.AddField(
            model_name='seller',
            name='all_countries',
            field=models.BooleanField(default=False, verbose_name='Все страны'),
        ),
        migrations.AddField(
            model_name='seller',
            name='all_models',
            field=models.BooleanField(default=False, verbose_name='Все модели'),
        ),
        migrations.AlterField(
            model_name='request',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
