# Generated by Django 6.0.4 on 2026-04-27 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_seller_all_brands_seller_all_categories_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PartCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'verbose_name': 'Категория запчастей',
                'verbose_name_plural': 'Категории запчастей',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='seller',
            name='selected_brands',
            field=models.ManyToManyField(blank=True, related_name='multi_sellers', to='core.brand', verbose_name='Выбранные марки'),
        ),
        migrations.AddField(
            model_name='seller',
            name='selected_countries',
            field=models.ManyToManyField(blank=True, related_name='multi_sellers', to='core.country', verbose_name='Выбранные страны'),
        ),
        migrations.AddField(
            model_name='seller',
            name='selected_models',
            field=models.ManyToManyField(blank=True, related_name='multi_sellers', to='core.carmodel', verbose_name='Выбранные модели'),
        ),
        migrations.AddField(
            model_name='seller',
            name='selected_categories',
            field=models.ManyToManyField(blank=True, related_name='sellers', to='core.partcategory', verbose_name='Выбранные категории'),
        ),
    ]
