# Generated by Django 6.0.4 on 2026-04-28 08:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_partcategory_seller_selected_brands_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='seller',
            options={'ordering': ['dispatch_priority', 'id', 'name'], 'verbose_name': 'Продавец', 'verbose_name_plural': 'Продавцы'},
        ),
        migrations.AddField(
            model_name='seller',
            name='dispatch_priority',
            field=models.PositiveIntegerField(default=1000, help_text='Чем меньше число, тем раньше продавец получает заявку в волнах рассылки.', verbose_name='Приоритет рассылки'),
        ),
        migrations.AlterUniqueTogether(
            name='match',
            unique_together={('request', 'seller')},
        ),
        migrations.CreateModel(
            name='RequestDispatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wave_number', models.PositiveIntegerField(verbose_name='Номер волны')),
                ('position_number', models.PositiveIntegerField(verbose_name='Позиция в очереди')),
                ('status', models.CharField(choices=[('queued', 'В очереди'), ('sent', 'Отправлено')], default='queued', max_length=20, verbose_name='Статус')),
                ('scheduled_at', models.DateTimeField(verbose_name='Запланировано на')),
                ('sent_at', models.DateTimeField(blank=True, null=True, verbose_name='Отправлено в')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dispatches', to='core.request', verbose_name='Заявка')),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dispatches', to='core.seller', verbose_name='Продавец')),
            ],
            options={
                'verbose_name': 'Очередь рассылки заявки',
                'verbose_name_plural': 'Очередь рассылки заявок',
                'ordering': ['request', 'position_number'],
                'unique_together': {('request', 'seller')},
            },
        ),
    ]
