# Generated by Django 6.0.4 on 2026-04-28 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_seller_options_seller_dispatch_priority_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BroadcastSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mode', models.CharField(choices=[('off', 'OFF — рассылка выключена'), ('test', 'TEST — только тестовые продавцы'), ('live', 'LIVE — боевая рассылка')], default='off', max_length=10, verbose_name='Режим рассылки')),
                ('wave_size', models.PositiveIntegerField(default=10, help_text='Сколько продавцов получает заявку в одной волне.', verbose_name='Размер волны')),
                ('wave_interval_minutes', models.PositiveIntegerField(default=5, help_text='Через сколько минут отправлять следующую волну.', verbose_name='Интервал между волнами, минут')),
                ('emergency_stop', models.BooleanField(default=False, help_text='Если включено, все следующие волны рассылки должны быть остановлены.', verbose_name='Emergency Stop')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
            ],
            options={
                'verbose_name': 'Broadcast Control',
                'verbose_name_plural': 'Broadcast Control',
            },
        ),
        migrations.AddField(
            model_name='seller',
            name='is_test_seller',
            field=models.BooleanField(default=False, help_text='Используется только в TEST-режиме рассылки.', verbose_name='Тестовый продавец'),
        ),
        migrations.AddField(
            model_name='seller',
            name='receive_requests',
            field=models.BooleanField(default=False, help_text='Участвует в боевой LIVE-рассылке заявок.', verbose_name='Получает заявки'),
        ),
        migrations.AlterField(
            model_name='requestdispatch',
            name='status',
            field=models.CharField(choices=[('queued', 'В очереди'), ('sent', 'Отправлено'), ('paused', 'Остановлено'), ('failed', 'Ошибка')], default='queued', max_length=20, verbose_name='Статус'),
        ),
    ]
