# Generated by Django 6.0.4 on 2026-04-29 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_broadcastsettings_seller_is_test_seller_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='seller',
            name='market_location',
            field=models.CharField(blank=True, max_length=255, verbose_name='Локация / бутик'),
        ),
        migrations.AddField(
            model_name='seller',
            name='notes',
            field=models.TextField(blank=True, verbose_name='Примечания'),
        ),
        migrations.AddField(
            model_name='seller',
            name='phone2',
            field=models.CharField(blank=True, max_length=20, verbose_name='Доп. телефон'),
        ),
        migrations.AddField(
            model_name='seller',
            name='seller_type',
            field=models.CharField(choices=[('seller', 'Продавец запчастей'), ('service', 'Сервис / СТО'), ('both', 'Продавец + сервис')], default='seller', max_length=20, verbose_name='Тип продавца'),
        ),
    ]
