# Generated by Django 6.0.4 on 2026-04-29 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_seller_market_location_seller_notes_seller_phone2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='seller',
            name='must_change_password',
            field=models.BooleanField(default=True, verbose_name='Требует смены пароля'),
        ),
        migrations.AddField(
            model_name='seller',
            name='password_hash',
            field=models.CharField(blank=True, max_length=255, verbose_name='Хэш пароля'),
        ),
    ]
