# Generated by Django 6.0.4 on 2026-05-01 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_seller_must_change_password_seller_password_hash'),
    ]

    operations = [
        migrations.CreateModel(
            name='WhatsAppMessageLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('request_id', models.IntegerField(blank=True, null=True)),
                ('seller_name', models.CharField(max_length=255)),
                ('phone_clean', models.CharField(max_length=20)),
                ('is_success', models.BooleanField(default=False)),
                ('status_text', models.CharField(blank=True, max_length=50)),
                ('message_id', models.CharField(blank=True, max_length=255)),
                ('error_text', models.TextField(blank=True)),
            ],
        ),
    ]
