# Generated by Django 6.0.5 on 2026-06-27 08:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_feedback'),
    ]

    operations = [
        migrations.CreateModel(
            name='RequestPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='request_photos/', verbose_name='Фото')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Загружено')),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='core.request', verbose_name='Заявка')),
            ],
            options={
                'verbose_name': 'Фото заявки',
                'verbose_name_plural': 'Фото заявок',
                'ordering': ['created_at'],
            },
        ),
    ]
