# Generated by Django 6.0.5 on 2026-07-04 08:59

from django.db import migrations, models
from django.utils.crypto import get_random_string


def populate_short_tokens(apps, schema_editor):
    Request = apps.get_model('core', 'Request')
    allowed_chars = 'abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789'
    used_tokens = set(
        Request.objects.exclude(short_token__isnull=True)
        .exclude(short_token='')
        .values_list('short_token', flat=True)
    )

    for req in Request.objects.filter(short_token__isnull=True):
        while True:
            token = get_random_string(6, allowed_chars=allowed_chars)
            if token in used_tokens:
                continue
            used_tokens.add(token)
            req.short_token = token
            req.save(update_fields=['short_token'])
            break


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_request_access_token_buyerportalaccess'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='short_token',
            field=models.CharField(blank=True, db_index=True, max_length=12, null=True, unique=True),
        ),
        migrations.RunPython(populate_short_tokens, migrations.RunPython.noop),
    ]
