# Generated by Django 6.0.5 on 2026-07-07 09:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_request_short_token'),
    ]

    operations = [
        migrations.CreateModel(
            name='InstagramPublication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='instagram_stories/', verbose_name='Карточка Story')),
                ('caption', models.TextField(blank=True, default='', verbose_name='Безопасный текст')),
                ('status', models.CharField(choices=[('draft', 'Черновик'), ('approved', 'Одобрено'), ('publishing', 'Публикуется'), ('published', 'Опубликовано'), ('failed', 'Ошибка'), ('cancelled', 'Отменено')], default='draft', max_length=20, verbose_name='Статус')),
                ('instagram_container_id', models.CharField(blank=True, default='', max_length=64, verbose_name='Instagram container ID')),
                ('instagram_media_id', models.CharField(blank=True, default='', max_length=64, verbose_name='Instagram media ID')),
                ('error_message', models.TextField(blank=True, default='', verbose_name='Текст ошибки')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('published_at', models.DateTimeField(blank=True, null=True, verbose_name='Опубликовано')),
                ('request', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='instagram_publication', to='core.request', verbose_name='Заявка')),
            ],
            options={
                'verbose_name': 'Публикация Instagram',
                'verbose_name_plural': 'Публикации Instagram',
                'ordering': ['-created_at'],
            },
        ),
    ]
