# Generated by Django 6.0.5 on 2026-07-13 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_instagrampublication_retry_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='SellerLead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('instagram_username', models.CharField(blank=True, default='', max_length=150, verbose_name='Instagram username')),
                ('instagram_url', models.URLField(blank=True, default='', max_length=500, verbose_name='Ссылка на Instagram')),
                ('whatsapp', models.CharField(blank=True, default='', max_length=20, verbose_name='WhatsApp')),
                ('city', models.CharField(blank=True, default='', max_length=100, verbose_name='Город')),
                ('category', models.CharField(blank=True, default='', max_length=100, verbose_name='Категория запчастей')),
                ('car_brands', models.CharField(blank=True, default='', max_length=255, verbose_name='Марки автомобилей')),
                ('profile_description', models.TextField(blank=True, default='', verbose_name='Описание профиля Instagram')),
                ('website_url', models.URLField(blank=True, default='', max_length=500, verbose_name='Сайт / Taplink / Linktree')),
                ('source_url', models.URLField(blank=True, default='', max_length=500, verbose_name='Источник контакта')),
                ('source_type', models.CharField(choices=[('instagram_search', 'Поиск в Instagram'), ('instagram_hashtag', 'Хэштег Instagram'), ('instagram_profile', 'Профиль Instagram'), ('instagram_post', 'Публикация Instagram'), ('web_search', 'Веб-поиск'), ('manual', 'Вручную'), ('other', 'Другое')], default='manual', max_length=32, verbose_name='Тип источника')),
                ('status', models.CharField(choices=[('new', 'Найден'), ('needs_review', 'Требует проверки'), ('verified', 'Проверен'), ('no_whatsapp', 'Нет WhatsApp'), ('contacted', 'Написали'), ('replied', 'Ответил'), ('interested', 'Заинтересован'), ('registered', 'Зарегистрирован'), ('rejected', 'Отказался'), ('duplicate', 'Дубликат'), ('not_seller', 'Не продавец')], default='needs_review', max_length=20, verbose_name='Статус')),
                ('notes', models.TextField(blank=True, default='', verbose_name='Комментарий оператора')),
                ('collected_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата обнаружения')),
                ('checked_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата проверки')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
            ],
            options={
                'verbose_name': 'Потенциальный продавец',
                'verbose_name_plural': 'Потенциальные продавцы',
                'ordering': ['-collected_at', '-created_at'],
                'indexes': [models.Index(fields=['status'], name='core_seller_status_51569c_idx'), models.Index(fields=['city'], name='core_seller_city_fbfacd_idx'), models.Index(fields=['category'], name='core_seller_categor_8c95a6_idx'), models.Index(fields=['instagram_username'], name='core_seller_instagr_3fb277_idx'), models.Index(fields=['whatsapp'], name='core_seller_whatsap_9183d8_idx'), models.Index(fields=['collected_at'], name='core_seller_collect_4a7458_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('instagram_username__gt', '')), fields=('instagram_username',), name='unique_sellerlead_instagram_username'), models.UniqueConstraint(condition=models.Q(('whatsapp__gt', '')), fields=('whatsapp',), name='unique_sellerlead_whatsapp')],
            },
        ),
    ]
