# Generated by Django 6.0.5 on 2026-07-13 04:10

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_sellerlead'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sellerlead',
            name='collected_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата обнаружения'),
        ),
    ]
