# Generated by Django 6.0.5 on 2026-07-13 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_sellerlead_collected_at_default'),
    ]

    operations = [
        migrations.AddField(
            model_name='sellerlead',
            name='whatsapp_confidence',
            field=models.CharField(blank=True, choices=[('high', 'Высокая'), ('medium', 'Средняя'), ('low', 'Низкая')], default='', max_length=10, verbose_name='Уверенность WhatsApp'),
        ),
        migrations.AddField(
            model_name='sellerlead',
            name='whatsapp_found_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата обнаружения WhatsApp'),
        ),
        migrations.AddField(
            model_name='sellerlead',
            name='whatsapp_source_text',
            field=models.TextField(blank=True, default='', verbose_name='Фрагмент текста с WhatsApp'),
        ),
        migrations.AddField(
            model_name='sellerlead',
            name='whatsapp_source_url',
            field=models.URLField(blank=True, default='', max_length=500, verbose_name='Источник WhatsApp'),
        ),
    ]
