# Generated by Django 6.0.5 on 2026-07-13 09:20

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_sellerlead_whatsapp_evidence'),
    ]

    operations = [
        migrations.CreateModel(
            name='SellerLeadContactCandidate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact_type', models.CharField(choices=[('whatsapp', 'WhatsApp'), ('phone', 'Телефон')], default='whatsapp', max_length=16, verbose_name='Тип контакта')),
                ('value', models.CharField(max_length=20, verbose_name='Значение')),
                ('role', models.CharField(choices=[('unknown', 'Не указано'), ('shop', 'Магазин'), ('service', 'Сервис'), ('sales', 'Продажи'), ('warehouse', 'Склад'), ('administration', 'Администрация')], default='unknown', max_length=20, verbose_name='Назначение')),
                ('label', models.CharField(blank=True, default='', max_length=255, verbose_name='Описание')),
                ('confidence', models.CharField(choices=[('high', 'Высокая'), ('medium', 'Средняя'), ('low', 'Низкая')], max_length=10, verbose_name='Уверенность')),
                ('source_url', models.URLField(blank=True, default='', max_length=500, verbose_name='URL источника')),
                ('source_text', models.TextField(blank=True, default='', verbose_name='Фрагмент доказательства')),
                ('source_type', models.CharField(choices=[('instagram_snippet', 'Сниппет Instagram'), ('wa_me', 'wa.me'), ('website', 'Сайт'), ('directory', 'Справочник'), ('facebook', 'Facebook'), ('manual', 'Вручную'), ('other', 'Другое')], default='other', max_length=32, verbose_name='Тип источника')),
                ('status', models.CharField(choices=[('pending', 'Ожидает проверки'), ('approved', 'Подтверждён'), ('rejected', 'Отклонён'), ('conflict', 'Конфликт')], default='pending', max_length=16, verbose_name='Статус')),
                ('is_primary', models.BooleanField(default=False, verbose_name='Основной контакт')),
                ('found_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата обнаружения')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата проверки')),
                ('notes', models.TextField(blank=True, default='', verbose_name='Комментарий')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('seller_lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contact_candidates', to='core.sellerlead', verbose_name='Потенциальный продавец')),
            ],
            options={
                'verbose_name': 'Кандидат контакта',
                'verbose_name_plural': 'Кандидаты контактов',
                'ordering': ['-found_at', '-created_at'],
                'indexes': [models.Index(fields=['seller_lead', 'status'], name='core_seller_seller__6b5fc4_idx'), models.Index(fields=['value'], name='core_seller_value_50f405_idx'), models.Index(fields=['confidence'], name='core_seller_confide_660dbb_idx'), models.Index(fields=['is_primary'], name='core_seller_is_prim_57542f_idx'), models.Index(fields=['found_at'], name='core_seller_found_a_258e1d_idx')],
                'constraints': [models.UniqueConstraint(fields=('seller_lead', 'contact_type', 'value'), name='unique_sellerlead_contact_candidate_value'), models.UniqueConstraint(condition=models.Q(('is_primary', True)), fields=('seller_lead',), name='unique_sellerlead_primary_contact_candidate')],
            },
        ),
    ]
