# Generated by Django 6.0.5 on 2026-07-14 05:31

import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_sellerleadcontactcandidate'),
    ]

    operations = [
        migrations.CreateModel(
            name='SellerLeadPipelineRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('run_uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='UUID запуска')),
                ('trigger', models.CharField(choices=[('manual', 'Ручной'), ('cron', 'Cron')], default='manual', max_length=16, verbose_name='Источник')),
                ('status', models.CharField(choices=[('running', 'Выполняется'), ('success', 'Успешно'), ('partial', 'Частично'), ('failed', 'Ошибка'), ('skipped', 'Пропущен')], default='running', max_length=16, verbose_name='Статус')),
                ('is_dry_run', models.BooleanField(default=False, verbose_name='Dry-run')),
                ('city', models.CharField(max_length=100, verbose_name='Город')),
                ('category', models.CharField(max_length=100, verbose_name='Категория')),
                ('search_limit', models.PositiveSmallIntegerField(verbose_name='Лимит поиска')),
                ('lead_limit', models.PositiveSmallIntegerField(verbose_name='Лимит лидов')),
                ('max_queries_per_lead', models.PositiveSmallIntegerField(verbose_name='Лимит запросов на лид')),
                ('skip_discovery', models.BooleanField(default=False, verbose_name='Пропуск discovery')),
                ('skip_enrichment', models.BooleanField(default=False, verbose_name='Пропуск enrichment')),
                ('cooldown_minutes', models.PositiveIntegerField(default=0, verbose_name='Cooldown (мин)')),
                ('force_run', models.BooleanField(default=False, verbose_name='Force run')),
                ('started_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Начало')),
                ('finished_at', models.DateTimeField(blank=True, null=True, verbose_name='Окончание')),
                ('discovery_stats', models.JSONField(blank=True, default=dict, verbose_name='Статистика discovery')),
                ('enrichment_stats', models.JSONField(blank=True, default=dict, verbose_name='Статистика enrichment')),
                ('created_lead_ids', models.JSONField(blank=True, default=list, verbose_name='Созданные лиды (ID)')),
                ('error_message', models.TextField(blank=True, default='', verbose_name='Сообщение об ошибке')),
                ('skip_reason', models.TextField(blank=True, default='', verbose_name='Причина пропуска')),
            ],
            options={
                'verbose_name': 'Запуск SellerLead pipeline',
                'verbose_name_plural': 'Запуски SellerLead pipeline',
                'ordering': ['-started_at'],
            },
        ),
    ]
