# Generated by Django 6.0.5 on 2026-07-15 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_sellerleadpipelinerun'),
    ]

    operations = [
        migrations.AddField(
            model_name='sellerleadpipelinerun',
            name='search_term',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='Поисковый термин'),
        ),
        migrations.AddField(
            model_name='sellerleadpipelinerun',
            name='rotation_enabled',
            field=models.BooleanField(default=False, verbose_name='Ротация включена'),
        ),
        migrations.AddField(
            model_name='sellerleadpipelinerun',
            name='rotation_slug',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Профиль ротации'),
        ),
        migrations.AddField(
            model_name='sellerleadpipelinerun',
            name='rotation_index',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Индекс ротации'),
        ),
    ]
