# Generated by Django 6.0.5 on 2026-07-15 09:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_sellerleadpipelinerun_rotation_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='BuyerContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_normalized', models.CharField(max_length=11, unique=True, verbose_name='Нормализованный телефон')),
                ('primary_country', models.CharField(blank=True, default='', max_length=100, verbose_name='Основная страна')),
                ('primary_city', models.CharField(blank=True, default='', max_length=100, verbose_name='Основной город')),
                ('first_request_at', models.DateTimeField(blank=True, null=True, verbose_name='Первая заявка')),
                ('last_request_at', models.DateTimeField(blank=True, null=True, verbose_name='Последняя заявка')),
                ('requests_count', models.PositiveIntegerField(default=0, verbose_name='Количество заявок')),
                ('last_search_scope', models.CharField(blank=True, choices=[('city', 'Только мой город'), ('kazakhstan', 'Весь Казахстан'), ('custom', 'Выбрать города')], default='', max_length=20, verbose_name='Последний режим поиска')),
                ('city_scope_requests_count', models.PositiveIntegerField(default=0, verbose_name='Заявок: только город')),
                ('kazakhstan_scope_requests_count', models.PositiveIntegerField(default=0, verbose_name='Заявок: весь Казахстан')),
                ('custom_scope_requests_count', models.PositiveIntegerField(default=0, verbose_name='Заявок: выбранные города')),
                ('status', models.CharField(choices=[('active', 'Активный'), ('invalid_phone', 'Некорректный телефон'), ('whatsapp_unavailable', 'WhatsApp недоступен'), ('unsubscribed', 'Отписался'), ('blocked', 'Заблокирован')], default='active', max_length=32, verbose_name='Статус')),
                ('source', models.CharField(choices=[('request', 'Заявка'), ('import', 'Импорт'), ('admin', 'Админ')], default='request', max_length=16, verbose_name='Источник')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлён')),
                ('portal_access', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='buyer_contact', to='core.buyerportalaccess', verbose_name='Доступ buyer portal')),
            ],
            options={
                'verbose_name': 'Контакт покупателя',
                'verbose_name_plural': 'Контакты покупателей',
                'ordering': ('-last_request_at', '-id'),
            },
        ),
        migrations.CreateModel(
            name='BuyerCityInterest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(blank=True, default='', max_length=100, verbose_name='Город')),
                ('city_normalized', models.CharField(max_length=100, verbose_name='Город (нормализованный)')),
                ('interest_type', models.CharField(choices=[('request_city', 'Город заявки'), ('selected_city', 'Выбранный город')], max_length=20, verbose_name='Тип интереса')),
                ('first_seen_at', models.DateTimeField(blank=True, null=True, verbose_name='Первое появление')),
                ('last_seen_at', models.DateTimeField(blank=True, null=True, verbose_name='Последнее появление')),
                ('requests_count', models.PositiveIntegerField(default=0, verbose_name='Количество заявок')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлён')),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='city_interests', to='core.buyercontact', verbose_name='Покупатель')),
            ],
            options={
                'verbose_name': 'Интерес к городу',
                'verbose_name_plural': 'Интересы к городам',
                'ordering': ('-last_seen_at', '-id'),
                'indexes': [models.Index(fields=['city_normalized', 'interest_type'], name='buyer_city_norm_type_idx')],
                'constraints': [models.UniqueConstraint(fields=('buyer', 'city_normalized', 'interest_type'), name='unique_buyer_city_interest')],
            },
        ),
        migrations.CreateModel(
            name='BuyerCategoryInterest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(blank=True, default='', max_length=100, verbose_name='Категория')),
                ('category_normalized', models.CharField(max_length=100, verbose_name='Категория (нормализованная)')),
                ('first_seen_at', models.DateTimeField(blank=True, null=True, verbose_name='Первое появление')),
                ('last_seen_at', models.DateTimeField(blank=True, null=True, verbose_name='Последнее появление')),
                ('requests_count', models.PositiveIntegerField(default=0, verbose_name='Количество заявок')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлён')),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category_interests', to='core.buyercontact', verbose_name='Покупатель')),
            ],
            options={
                'verbose_name': 'Интерес к категории',
                'verbose_name_plural': 'Интересы к категориям',
                'ordering': ('-last_seen_at', '-id'),
                'indexes': [models.Index(fields=['category_normalized'], name='buyer_category_norm_idx')],
                'constraints': [models.UniqueConstraint(fields=('buyer', 'category_normalized'), name='unique_buyer_category_interest')],
            },
        ),
        migrations.CreateModel(
            name='BuyerVehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transport_type', models.CharField(choices=[('car', 'Легковые'), ('truck', 'Грузовые')], max_length=10, verbose_name='Тип транспорта')),
                ('brand', models.CharField(blank=True, default='', max_length=100, verbose_name='Марка')),
                ('model', models.CharField(blank=True, default='', max_length=100, verbose_name='Модель')),
                ('brand_normalized', models.CharField(max_length=100, verbose_name='Марка (нормализованная)')),
                ('model_normalized', models.CharField(max_length=100, verbose_name='Модель (нормализованная)')),
                ('first_seen_at', models.DateTimeField(blank=True, null=True, verbose_name='Первое появление')),
                ('last_seen_at', models.DateTimeField(blank=True, null=True, verbose_name='Последнее появление')),
                ('requests_count', models.PositiveIntegerField(default=0, verbose_name='Количество заявок')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлён')),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vehicles', to='core.buyercontact', verbose_name='Покупатель')),
            ],
            options={
                'verbose_name': 'Автомобиль покупателя',
                'verbose_name_plural': 'Автомобили покупателей',
                'ordering': ('-last_seen_at', '-id'),
                'indexes': [models.Index(fields=['brand_normalized', 'model_normalized'], name='buyer_vehicle_brand_model_idx')],
                'constraints': [models.UniqueConstraint(fields=('buyer', 'transport_type', 'brand_normalized', 'model_normalized'), name='unique_buyer_vehicle')],
            },
        ),
        migrations.CreateModel(
            name='ContactConsent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel', models.CharField(choices=[('whatsapp', 'WhatsApp')], max_length=16, verbose_name='Канал')),
                ('purpose', models.CharField(choices=[('service', 'Сервисные'), ('information', 'Информационные'), ('marketing', 'Рекламные')], max_length=16, verbose_name='Цель')),
                ('status', models.CharField(choices=[('unknown', 'Неизвестно'), ('granted', 'Дано'), ('revoked', 'Отозвано')], default='unknown', max_length=16, verbose_name='Статус')),
                ('source', models.CharField(blank=True, choices=[('request_form', 'Форма заявки'), ('registration', 'Регистрация'), ('buyer_portal', 'Buyer portal'), ('whatsapp', 'WhatsApp'), ('admin', 'Админ'), ('import', 'Импорт')], default='', max_length=20, verbose_name='Источник')),
                ('consent_text_version', models.CharField(blank=True, default='', max_length=50, verbose_name='Версия текста согласия')),
                ('evidence_reference', models.CharField(blank=True, default='', max_length=255, verbose_name='Ссылка на доказательство')),
                ('consented_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата согласия')),
                ('revoked_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата отзыва')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлён')),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consents', to='core.buyercontact', verbose_name='Покупатель')),
            ],
            options={
                'verbose_name': 'Согласие на контакт',
                'verbose_name_plural': 'Согласия на контакт',
                'ordering': ('-updated_at', '-id'),
                'constraints': [models.UniqueConstraint(fields=('buyer', 'channel', 'purpose'), name='unique_buyer_consent_purpose')],
            },
        ),
    ]
