# Generated by Django 6.0.5 on 2026-07-15 10:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_buyer_contact_models'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='buyer_contact',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requests', to='core.buyercontact', verbose_name='Покупатель'),
        ),
    ]
