# Generated by Django 6.0.5 on 2026-07-15 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_request_buyer_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='buyercontact',
            name='is_test_contact',
            field=models.BooleanField(default=False, help_text='Тестовые контакты должны исключаться из будущих рекламных аудиторий.', verbose_name='Тестовый контакт'),
        ),
    ]
