# Generated by Django 6.0.5 on 2026-07-16 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0028_buyercontact_is_test_contact'),
    ]

    operations = [
        migrations.CreateModel(
            name='BuyerAudience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True, verbose_name='Название аудитории')),
                ('description', models.TextField(blank=True, default='', verbose_name='Описание')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна')),
                ('criteria', models.JSONField(blank=True, default=dict, verbose_name='Критерии аудитории')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создана')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлена')),
            ],
            options={
                'verbose_name': 'Сохранённая аудитория покупателей',
                'verbose_name_plural': 'Сохранённые аудитории покупателей',
                'ordering': ('name',),
            },
        ),
    ]
