# Generated by Django 6.0.5 on 2026-07-16 05:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0029_buyeraudience'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BuyerBroadcastCampaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название кампании')),
                ('description', models.TextField(blank=True, default='', verbose_name='Описание')),
                ('mode', models.CharField(choices=[('test', 'Тестовая')], default='test', max_length=20, verbose_name='Режим')),
                ('status', models.CharField(choices=[('draft', 'Черновик'), ('ready', 'Готова к тесту'), ('queued', 'Поставлена в очередь'), ('sending', 'Отправляется'), ('completed', 'Завершена'), ('completed_with_errors', 'Завершена с ошибками'), ('cancelled', 'Отменена')], default='draft', max_length=30, verbose_name='Статус')),
                ('template_name', models.CharField(max_length=150, verbose_name='Имя шаблона WhatsApp')),
                ('template_language', models.CharField(default='ru', max_length=20, verbose_name='Язык шаблона')),
                ('template_body_parameters', models.JSONField(blank=True, default=list, verbose_name='Параметры шаблона')),
                ('message_preview', models.TextField(blank=True, default='', help_text='Используется только для проверки администратором и не отправляется как свободный текст.', verbose_name='Текст для предварительного просмотра')),
                ('queued_at', models.DateTimeField(blank=True, null=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='buyer_broadcast_campaigns', to=settings.AUTH_USER_MODEL, verbose_name='Создал')),
                ('test_contacts', models.ManyToManyField(blank=True, related_name='test_broadcast_campaigns', to='core.buyercontact', verbose_name='Тестовые получатели')),
            ],
            options={
                'verbose_name': 'Тестовая WhatsApp-кампания покупателей',
                'verbose_name_plural': 'Тестовые WhatsApp-кампании покупателей',
                'ordering': ('-created_at', '-id'),
            },
        ),
        migrations.CreateModel(
            name='BuyerBroadcastRecipient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_snapshot', models.CharField(max_length=11)),
                ('masked_phone_snapshot', models.CharField(max_length=20)),
                ('status', models.CharField(choices=[('queued', 'В очереди'), ('sending', 'Отправляется'), ('sent', 'Отправлено'), ('failed', 'Ошибка'), ('skipped', 'Пропущено')], default='queued', max_length=20)),
                ('skip_reason', models.CharField(blank=True, default='', max_length=100)),
                ('provider_message_id', models.CharField(blank=True, default='', max_length=255)),
                ('error_message', models.TextField(blank=True, default='')),
                ('attempts_count', models.PositiveIntegerField(default=0)),
                ('queued_at', models.DateTimeField(blank=True, null=True)),
                ('last_attempt_at', models.DateTimeField(blank=True, null=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='broadcast_recipients', to='core.buyercontact')),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipients', to='core.buyerbroadcastcampaign')),
            ],
            options={
                'verbose_name': 'Получатель тестовой рассылки',
                'verbose_name_plural': 'Получатели тестовых рассылок',
                'ordering': ('campaign_id', 'id'),
                'indexes': [models.Index(fields=['campaign', 'status'], name='bb_rec_campaign_status'), models.Index(fields=['status', 'queued_at'], name='bb_rec_status_queued')],
                'constraints': [models.UniqueConstraint(fields=('campaign', 'buyer'), name='unique_buyer_broadcast_recipient')],
            },
        ),
    ]
