# Generated by Django 6.0.5 on 2026-09-01 08:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def _digits(value):
    return ''.join(ch for ch in str(value or '') if ch.isdigit())


def link_sellers_to_matching_users(apps, schema_editor):
    Seller = apps.get_model('core', 'Seller')
    User = apps.get_model(settings.AUTH_USER_MODEL)

    for seller in Seller.objects.all().iterator():
        normalized = _digits(seller.whatsapp)[:20]
        if normalized != (seller.whatsapp or ''):
            seller.whatsapp = normalized
            seller.save(update_fields=['whatsapp'])

    users_by_phone = {}
    ambiguous_user_phones = set()
    for user in User.objects.all().iterator():
        phone = _digits(user.username)
        if not phone:
            continue
        if phone in users_by_phone or phone in ambiguous_user_phones:
            users_by_phone.pop(phone, None)
            ambiguous_user_phones.add(phone)
            continue
        users_by_phone[phone] = user.pk

    sellers_by_phone = {}
    ambiguous_seller_phones = set()
    for seller in Seller.objects.filter(user__isnull=True).iterator():
        phone = _digits(seller.whatsapp)
        if not phone:
            continue
        if phone in sellers_by_phone or phone in ambiguous_seller_phones:
            sellers_by_phone.pop(phone, None)
            ambiguous_seller_phones.add(phone)
            continue
        sellers_by_phone[phone] = seller

    linked_user_ids = set(
        Seller.objects.exclude(user_id=None).values_list('user_id', flat=True)
    )

    for phone, seller in sellers_by_phone.items():
        if phone in ambiguous_user_phones or phone in ambiguous_seller_phones:
            continue
        user_id = users_by_phone.get(phone)
        if not user_id or user_id in linked_user_ids:
            continue
        seller.user_id = user_id
        seller.password_hash = ''
        seller.must_change_password = False
        seller.save(update_fields=['user', 'password_hash', 'must_change_password'])
        linked_user_ids.add(user_id)


def unlink_sellers(apps, schema_editor):
    Seller = apps.get_model('core', 'Seller')
    Seller.objects.exclude(user_id=None).update(user=None)


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0034_instagrampublication_image_blank'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='seller',
            name='user',
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='request_seller',
                to=settings.AUTH_USER_MODEL,
                verbose_name='Единая учётная запись',
            ),
        ),
        migrations.RunPython(link_sellers_to_matching_users, unlink_sellers),
    ]
