# Generated by Django 6.0.5

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0035_seller_unified_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PlatformHelpConversation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='Публичный ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлён')),
                ('user', models.ForeignKey(
                    blank=True,
                    null=True,
                    on_delete=django.db.models.deletion.SET_NULL,
                    related_name='platform_help_conversations',
                    to=settings.AUTH_USER_MODEL,
                    verbose_name='Пользователь',
                )),
            ],
            options={
                'verbose_name': 'Диалог справки ZPT.KZ',
                'verbose_name_plural': 'Диалоги справки ZPT.KZ',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PlatformHelpMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(
                    choices=[('user', 'Пользователь'), ('assistant', 'Помощник')],
                    max_length=16,
                    verbose_name='Роль',
                )),
                ('input_mode', models.CharField(
                    choices=[('text', 'Текст'), ('voice', 'Голос'), ('system', 'Система')],
                    default='text',
                    max_length=16,
                    verbose_name='Способ ввода',
                )),
                ('content', models.TextField(verbose_name='Текст')),
                ('ai_model', models.CharField(blank=True, default='', max_length=100, verbose_name='Модель AI')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('conversation', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE,
                    related_name='messages',
                    to='core.platformhelpconversation',
                    verbose_name='Диалог',
                )),
            ],
            options={
                'verbose_name': 'Сообщение справки ZPT.KZ',
                'verbose_name_plural': 'Сообщения справки ZPT.KZ',
                'ordering': ['created_at', 'id'],
            },
        ),
        migrations.AddIndex(
            model_name='platformhelpmessage',
            index=models.Index(fields=['conversation', 'created_at'], name='core_help_msg_conv_created'),
        ),
    ]
