# Generated by Django 6.0.5 on 2026-09-04 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0036_platform_help'),
    ]

    operations = [
        migrations.AddField(
            model_name='platformhelpconversation',
            name='contact_source',
            field=models.CharField(blank=True, choices=[('seller', 'Профиль продавца'), ('user_input', 'Указан пользователем')], default='', max_length=20, verbose_name='Источник WhatsApp'),
        ),
        migrations.AddField(
            model_name='platformhelpconversation',
            name='contact_whatsapp',
            field=models.CharField(blank=True, default='', max_length=20, verbose_name='WhatsApp для ответа'),
        ),
    ]
