# Generated by Django 6.0.5 on 2026-09-07 05:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0037_platformhelpconversation_contact_whatsapp'),
    ]

    operations = [
        migrations.CreateModel(
            name='SellerContactConsent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_normalized', models.CharField(db_index=True, max_length=11, verbose_name='Телефон')),
                ('channel', models.CharField(choices=[('whatsapp', 'WhatsApp')], max_length=16, verbose_name='Канал')),
                ('purpose', models.CharField(choices=[('service', 'Сервисные'), ('information', 'Информационные'), ('marketing', 'Рекламные')], max_length=16, verbose_name='Цель')),
                ('status', models.CharField(choices=[('unknown', 'Неизвестно'), ('granted', 'Дано'), ('revoked', 'Отозвано')], default='unknown', max_length=16, verbose_name='Статус')),
                ('source', models.CharField(blank=True, choices=[('request_form', 'Форма заявки'), ('registration', 'Регистрация'), ('buyer_portal', 'Buyer portal'), ('whatsapp', 'WhatsApp'), ('admin', 'Админ'), ('import', 'Импорт')], default='', max_length=20, verbose_name='Источник')),
                ('consent_text_version', models.CharField(blank=True, default='', max_length=50, verbose_name='Версия текста согласия')),
                ('evidence_reference', models.CharField(blank=True, default='', max_length=255, verbose_name='Ссылка на доказательство')),
                ('consented_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата согласия')),
                ('revoked_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата отзыва')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлён')),
                ('seller', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contact_consents', to='core.seller', verbose_name='Продавец')),
            ],
            options={
                'verbose_name': 'Согласие продавца на контакт',
                'verbose_name_plural': 'Согласия продавцов на контакт',
                'ordering': ('-updated_at', '-id'),
                'constraints': [models.UniqueConstraint(fields=('seller', 'phone_normalized', 'channel', 'purpose'), name='unique_seller_consent_purpose')],
            },
        ),
        migrations.CreateModel(
            name='WhatsAppInboundEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider_message_id', models.CharField(max_length=255, unique=True, verbose_name='ID сообщения WhatsApp')),
                ('phone_normalized', models.CharField(blank=True, db_index=True, default='', max_length=11, verbose_name='Телефон')),
                ('message_type', models.CharField(blank=True, default='', max_length=32, verbose_name='Тип сообщения')),
                ('button_text', models.CharField(blank=True, default='', max_length=255, verbose_name='Текст кнопки')),
                ('action', models.CharField(blank=True, choices=[('', '—'), ('seller_confirm_yes', 'Да, подтверждаю'), ('seller_confirm_no', 'Нет, отключить')], default='', max_length=32, verbose_name='Действие')),
                ('processing_status', models.CharField(choices=[('processed', 'Обработано'), ('ignored', 'Игнорировано'), ('unmatched', 'Продавец не найден'), ('ambiguous', 'Несколько продавцов'), ('error', 'Ошибка'), ('stale', 'Устарело')], default='ignored', max_length=16, verbose_name='Статус обработки')),
                ('provider_timestamp', models.DateTimeField(blank=True, null=True, verbose_name='Время у провайдера')),
                ('payload_hash', models.CharField(blank=True, default='', max_length=64, verbose_name='SHA-256 фрагмента payload')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('processed_at', models.DateTimeField(blank=True, null=True, verbose_name='Обработан')),
                ('seller', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='whatsapp_inbound_events', to='core.seller', verbose_name='Продавец')),
            ],
            options={
                'verbose_name': 'Входящее событие WhatsApp',
                'verbose_name_plural': 'Входящие события WhatsApp',
                'ordering': ('-created_at', '-id'),
                'indexes': [models.Index(fields=['processing_status', '-created_at'], name='core_wa_inbound_status_created')],
            },
        ),
    ]
