# Generated by Django 6.0.5 on 2026-09-07 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0038_seller_contact_consent_and_whatsapp_inbound'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactconsent',
            name='source',
            field=models.CharField(
                blank=True,
                choices=[
                    ('request_form', 'Форма заявки'),
                    ('registration', 'Регистрация'),
                    ('buyer_portal', 'Buyer portal'),
                    ('whatsapp', 'WhatsApp'),
                    ('admin', 'Админ'),
                    ('import', 'Импорт'),
                    ('seller_portal', 'Кабинет продавца'),
                ],
                default='',
                max_length=20,
                verbose_name='Источник',
            ),
        ),
        migrations.AlterField(
            model_name='sellercontactconsent',
            name='source',
            field=models.CharField(
                blank=True,
                choices=[
                    ('request_form', 'Форма заявки'),
                    ('registration', 'Регистрация'),
                    ('buyer_portal', 'Buyer portal'),
                    ('whatsapp', 'WhatsApp'),
                    ('admin', 'Админ'),
                    ('import', 'Импорт'),
                    ('seller_portal', 'Кабинет продавца'),
                ],
                default='',
                max_length=20,
                verbose_name='Источник',
            ),
        ),
    ]
