# Generated by Django 6.0.5 on 2026-09-11 08:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0039_seller_consent_source_seller_portal'),
    ]

    operations = [
        migrations.CreateModel(
            name='SellerRequestAccess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(db_index=True, max_length=64, unique=True, verbose_name='Токен ссылки продавца')),
                ('expires_at', models.DateTimeField(db_index=True, verbose_name='Срок действия')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('request', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='seller_access_links', to='core.request', verbose_name='Заявка')),
                ('seller', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='request_access_links', to='core.seller', verbose_name='Продавец')),
            ],
            options={
                'verbose_name': 'Ссылка заявки для продавца',
                'verbose_name_plural': 'Ссылки заявок для продавцов',
                'ordering': ['-created_at'],
            },
        ),
    ]
