# Generated by Django 6.0.5 on 2026-09-13 06:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0041_seller_request_page_consent_source'),
    ]

    operations = [
        migrations.CreateModel(
            name='SellerRequestPageEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('page_open', 'Открытие страницы'), ('whatsapp_click', 'Клик WhatsApp'), ('call_click', 'Клик звонка'), ('marketing_consent_yes', 'Согласие на предложения'), ('marketing_consent_no', 'Отказ от предложений'), ('out_of_stock', 'Нет в наличии'), ('cannot_fulfill', 'Не могу выполнить заявку')], max_length=32, verbose_name='Тип события')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('access', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='page_events', to='core.sellerrequestaccess', verbose_name='Ссылка доступа')),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seller_page_events', to='core.request', verbose_name='Заявка')),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='request_page_events', to='core.seller', verbose_name='Продавец')),
            ],
            options={
                'verbose_name': 'Событие страницы заявки продавца',
                'verbose_name_plural': 'События страницы заявки продавца',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['request', 'seller', 'event_type'], name='core_seller_request_219821_idx'), models.Index(fields=['access', 'event_type'], name='core_seller_access__12bb41_idx')],
                'constraints': [models.UniqueConstraint(fields=('access', 'event_type'), name='uniq_sr_page_event_access_type'), models.UniqueConstraint(condition=models.Q(('event_type__in', ['out_of_stock', 'cannot_fulfill'])), fields=('request', 'seller'), name='uniq_sr_page_outcome_request_seller')],
            },
        ),
    ]
