# Generated by Django 6.0.5 on 2026-09-13 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0042_seller_request_page_event'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='sellerrequestpageevent',
            constraint=models.UniqueConstraint(condition=models.Q(('event_type__in', ['marketing_consent_yes', 'marketing_consent_no'])), fields=('access',), name='uniq_sr_page_consent_access'),
        ),
    ]
