# Generated by Django 6.0.5 on 2026-10-01 05:20

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0046_guidefaqvote'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SellerLeadDuplicateMatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Оценка')),
                ('status', models.CharField(choices=[('possible', 'Возможный'), ('confirmed', 'Подтверждён'), ('rejected', 'Отклонён')], db_index=True, default='possible', max_length=16, verbose_name='Статус пары')),
                ('reasons', models.JSONField(blank=True, default=list, verbose_name='Причины')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('resolved_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата решения')),
            ],
            options={
                'verbose_name': 'Возможный дубль',
                'verbose_name_plural': 'Возможные дубли',
                'ordering': ['-score', '-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='SellerLeadEvidence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_name', models.CharField(db_index=True, max_length=64, verbose_name='Поле')),
                ('value', models.TextField(verbose_name='Значение')),
                ('normalized_value', models.TextField(blank=True, default='', verbose_name='Нормализованное значение')),
                ('confidence', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Уверенность')),
                ('extraction_method', models.CharField(choices=[('parser', 'Парсер'), ('search_result', 'Результат поиска'), ('ai', 'AI'), ('manual', 'Вручную'), ('seller', 'Продавец'), ('import', 'Импорт'), ('other', 'Другое')], default='other', max_length=32, verbose_name='Способ извлечения')),
                ('observed_at', models.DateTimeField(verbose_name='Наблюдалось')),
                ('is_selected', models.BooleanField(default=False, verbose_name='Выбранное значение')),
                ('is_owner_verified', models.BooleanField(default=False, verbose_name='Подтверждено владельцем')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
            ],
            options={
                'verbose_name': 'Доказательство',
                'verbose_name_plural': 'Доказательства',
                'ordering': ['-observed_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='SellerLeadLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.CharField(blank=True, default='', max_length=255, verbose_name='Внешний ID')),
                ('name', models.CharField(blank=True, default='', max_length=255, verbose_name='Название точки')),
                ('city', models.CharField(blank=True, db_index=True, default='', max_length=100, verbose_name='Город')),
                ('address', models.CharField(blank=True, default='', max_length=500, verbose_name='Адрес')),
                ('normalized_address', models.CharField(blank=True, db_index=True, default='', max_length=500, verbose_name='Нормализованный адрес')),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Широта')),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Долгота')),
                ('is_primary', models.BooleanField(default=False, verbose_name='Основная точка')),
                ('confidence', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Уверенность')),
                ('first_seen_at', models.DateTimeField(verbose_name='Первое наблюдение')),
                ('last_seen_at', models.DateTimeField(verbose_name='Последнее наблюдение')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
            ],
            options={
                'verbose_name': 'Локация найденного продавца',
                'verbose_name_plural': 'Локации найденных продавцов',
                'ordering': ['-is_primary', '-last_seen_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='SellerLeadSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_type', models.CharField(choices=[('brave_search', 'Brave Search'), ('web_search', 'Веб-поиск'), ('instagram', 'Instagram'), ('website', 'Сайт'), ('two_gis', '2GIS'), ('google_places', 'Google Places'), ('directory', 'Справочник'), ('manual', 'Вручную'), ('other', 'Другое')], max_length=32, verbose_name='Тип источника')),
                ('provider', models.CharField(blank=True, default='', max_length=64, verbose_name='Провайдер')),
                ('external_id', models.CharField(blank=True, db_index=True, default='', max_length=255, verbose_name='Внешний ID')),
                ('source_url', models.URLField(blank=True, default='', max_length=500, verbose_name='URL источника')),
                ('display_name', models.CharField(blank=True, default='', max_length=255, verbose_name='Название в источнике')),
                ('first_seen_at', models.DateTimeField(verbose_name='Первое наблюдение')),
                ('last_seen_at', models.DateTimeField(verbose_name='Последнее наблюдение')),
                ('fetched_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата загрузки')),
                ('source_confidence', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Уверенность источника')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='Метаданные')),
                ('raw_payload_hash', models.CharField(blank=True, db_index=True, default='', max_length=64, verbose_name='Хеш исходных данных')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
            ],
            options={
                'verbose_name': 'Источник найденного продавца',
                'verbose_name_plural': 'Источники найденных продавцов',
                'ordering': ['-last_seen_at', '-id'],
            },
        ),
        migrations.AlterModelOptions(
            name='sellerlead',
            options={'ordering': ['-collected_at', '-created_at'], 'verbose_name': 'Найденный продавец', 'verbose_name_plural': 'Найденные продавцы'},
        ),
        migrations.AddField(
            model_name='sellerlead',
            name='duplicate_of',
            field=models.ForeignKey(blank=True, help_text='Заполняется только после явного подтверждения дубля администратором.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='merged_duplicates', to='core.sellerlead', verbose_name='Подтверждённый дубль карточки'),
        ),
        migrations.AddField(
            model_name='sellerlead',
            name='last_classified_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Последняя классификация'),
        ),
        migrations.AddField(
            model_name='sellerlead',
            name='last_enriched_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Последнее обогащение'),
        ),
        migrations.AddField(
            model_name='sellerlead',
            name='last_seen_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='Последнее наблюдение'),
        ),
        migrations.AddField(
            model_name='sellerlead',
            name='lifecycle_status',
            field=models.CharField(choices=[('found', 'Найден'), ('enriched', 'Обогащён'), ('classified', 'Классифицирован'), ('ready_to_invite', 'Готов к приглашению'), ('invited', 'Приглашён'), ('claimed', 'Заявлен владельцем'), ('verified', 'Подтверждён'), ('active', 'Активный'), ('possible_duplicate', 'Возможный дубль'), ('duplicate', 'Дубль'), ('rejected', 'Отклонён'), ('unreachable', 'Недоступен'), ('closed', 'Закрыт')], db_index=True, default='found', help_text='Используется Seller Discovery. Поле «Статус» остаётся для текущего pipeline.', max_length=32, verbose_name='Жизненный цикл'),
        ),
        migrations.AddField(
            model_name='sellerlead',
            name='normalized_address',
            field=models.CharField(blank=True, default='', max_length=500, verbose_name='Нормализованный адрес'),
        ),
        migrations.AddField(
            model_name='sellerlead',
            name='normalized_domain',
            field=models.CharField(blank=True, db_index=True, default='', max_length=255, verbose_name='Нормализованный домен'),
        ),
        migrations.AddField(
            model_name='sellerlead',
            name='normalized_instagram',
            field=models.CharField(blank=True, db_index=True, default='', max_length=150, verbose_name='Нормализованный Instagram'),
        ),
        migrations.AddField(
            model_name='sellerlead',
            name='normalized_name',
            field=models.CharField(blank=True, db_index=True, default='', max_length=255, verbose_name='Нормализованное название'),
        ),
        migrations.AddField(
            model_name='sellerlead',
            name='normalized_phone',
            field=models.CharField(blank=True, db_index=True, default='', max_length=32, verbose_name='Нормализованный телефон'),
        ),
        migrations.AddField(
            model_name='sellerlead',
            name='overall_confidence',
            field=models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Общая уверенность'),
        ),
        migrations.AddConstraint(
            model_name='sellerlead',
            constraint=models.CheckConstraint(condition=models.Q(('overall_confidence__isnull', True), ('overall_confidence__lte', 100), _connector='OR'), name='sl_overall_confidence_lte_100'),
        ),
        migrations.AddField(
            model_name='sellerleadduplicatematch',
            name='lead_a',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='duplicate_matches_as_a', to='core.sellerlead', verbose_name='Карточка A'),
        ),
        migrations.AddField(
            model_name='sellerleadduplicatematch',
            name='lead_b',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='duplicate_matches_as_b', to='core.sellerlead', verbose_name='Карточка B'),
        ),
        migrations.AddField(
            model_name='sellerleadduplicatematch',
            name='resolved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_seller_lead_duplicates', to=settings.AUTH_USER_MODEL, verbose_name='Кто решил'),
        ),
        migrations.AddField(
            model_name='sellerleadevidence',
            name='seller_lead',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evidences', to='core.sellerlead', verbose_name='Найденный продавец'),
        ),
        migrations.AddField(
            model_name='sellerleadlocation',
            name='seller_lead',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='locations', to='core.sellerlead', verbose_name='Найденный продавец'),
        ),
        migrations.AddField(
            model_name='sellerleadsource',
            name='seller_lead',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sources', to='core.sellerlead', verbose_name='Найденный продавец'),
        ),
        migrations.AddField(
            model_name='sellerleadlocation',
            name='source',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='locations', to='core.sellerleadsource', verbose_name='Источник'),
        ),
        migrations.AddField(
            model_name='sellerleadevidence',
            name='source',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='evidences', to='core.sellerleadsource', verbose_name='Источник'),
        ),
        migrations.AddIndex(
            model_name='sellerleadduplicatematch',
            index=models.Index(fields=['status', 'score'], name='sl_dup_status_score_idx'),
        ),
        migrations.AddConstraint(
            model_name='sellerleadduplicatematch',
            constraint=models.UniqueConstraint(fields=('lead_a', 'lead_b'), name='uniq_sl_duplicate_pair'),
        ),
        migrations.AddConstraint(
            model_name='sellerleadduplicatematch',
            constraint=models.CheckConstraint(condition=models.Q(('lead_a_id__lt', models.F('lead_b_id'))), name='sl_dup_pair_ordered'),
        ),
        migrations.AddConstraint(
            model_name='sellerleadduplicatematch',
            constraint=models.CheckConstraint(condition=models.Q(('score__lte', 100)), name='sl_dup_score_lte_100'),
        ),
        migrations.AddIndex(
            model_name='sellerleadsource',
            index=models.Index(fields=['seller_lead', 'source_type'], name='sl_src_lead_type_idx'),
        ),
        migrations.AddIndex(
            model_name='sellerleadsource',
            index=models.Index(fields=['provider', 'external_id'], name='sl_src_prov_ext_idx'),
        ),
        migrations.AddIndex(
            model_name='sellerleadsource',
            index=models.Index(fields=['source_url'], name='sl_src_url_idx'),
        ),
        migrations.AddIndex(
            model_name='sellerleadsource',
            index=models.Index(fields=['last_seen_at'], name='sl_src_seen_idx'),
        ),
        migrations.AddConstraint(
            model_name='sellerleadsource',
            constraint=models.UniqueConstraint(condition=models.Q(('external_id', ''), _negated=True), fields=('source_type', 'provider', 'external_id'), name='uniq_sl_source_external_id'),
        ),
        migrations.AddConstraint(
            model_name='sellerleadsource',
            constraint=models.UniqueConstraint(condition=models.Q(('source_url', ''), _negated=True), fields=('seller_lead', 'source_url'), name='uniq_sl_source_url_per_lead'),
        ),
        migrations.AddConstraint(
            model_name='sellerleadsource',
            constraint=models.CheckConstraint(condition=models.Q(('source_confidence__isnull', True), ('source_confidence__lte', 100), _connector='OR'), name='sl_source_confidence_lte_100'),
        ),
        migrations.AddIndex(
            model_name='sellerleadlocation',
            index=models.Index(fields=['seller_lead', 'city'], name='sl_loc_lead_city_idx'),
        ),
        migrations.AddConstraint(
            model_name='sellerleadlocation',
            constraint=models.UniqueConstraint(condition=models.Q(('is_primary', True)), fields=('seller_lead',), name='uniq_sl_primary_location'),
        ),
        migrations.AddConstraint(
            model_name='sellerleadlocation',
            constraint=models.CheckConstraint(condition=models.Q(('confidence__isnull', True), ('confidence__lte', 100), _connector='OR'), name='sl_location_confidence_lte_100'),
        ),
        migrations.AddIndex(
            model_name='sellerleadevidence',
            index=models.Index(fields=['seller_lead', 'field_name'], name='sl_ev_lead_field_idx'),
        ),
        migrations.AddIndex(
            model_name='sellerleadevidence',
            index=models.Index(fields=['normalized_value'], name='sl_ev_norm_idx'),
        ),
        migrations.AddIndex(
            model_name='sellerleadevidence',
            index=models.Index(fields=['is_selected'], name='sl_ev_selected_idx'),
        ),
        migrations.AddConstraint(
            model_name='sellerleadevidence',
            constraint=models.UniqueConstraint(condition=models.Q(('is_selected', True)), fields=('seller_lead', 'field_name'), name='uniq_sl_selected_evidence'),
        ),
        migrations.AddConstraint(
            model_name='sellerleadevidence',
            constraint=models.CheckConstraint(condition=models.Q(('confidence__isnull', True), ('confidence__lte', 100), _connector='OR'), name='sl_evidence_confidence_lte_100'),
        ),
    ]
