# Generated by Django 6.0.5 on 2026-10-03 12:37

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0048_seller_discovery_foundation_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='sellerlead',
            name='business_type',
            field=models.CharField(choices=[('new_parts', 'Новые запчасти'), ('dismantler', 'Авторазбор / б/у'), ('mixed', 'Новые + б/у'), ('unknown', 'Не определено')], db_index=True, default='unknown', max_length=16, verbose_name='Тип бизнеса'),
        ),
        migrations.AddField(
            model_name='sellerlead',
            name='business_type_confidence',
            field=models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Уверенность типа бизнеса'),
        ),
        migrations.AddField(
            model_name='sellerlead',
            name='business_type_evidence',
            field=models.CharField(blank=True, default='', max_length=500, verbose_name='Основание типа бизнеса'),
        ),
        migrations.CreateModel(
            name='SellerLeadDiscoveredBrand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('confidence', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Уверенность')),
                ('source_kind', models.CharField(max_length=32, verbose_name='Откуда')),
                ('source_text', models.CharField(blank=True, default='', max_length=300, verbose_name='Фрагмент')),
                ('observed_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Определено')),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seller_lead_brand_links', to='core.brand', verbose_name='Марка')),
                ('seller_lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='brand_links', to='core.sellerlead', verbose_name='Найденный продавец')),
            ],
            options={
                'verbose_name': 'Найденная марка',
                'verbose_name_plural': 'Найденные марки',
            },
        ),
        migrations.AddField(
            model_name='sellerlead',
            name='discovered_brands',
            field=models.ManyToManyField(blank=True, related_name='discovered_seller_leads', through='core.SellerLeadDiscoveredBrand', to='core.brand', verbose_name='Найденные марки'),
        ),
        migrations.CreateModel(
            name='SellerLeadDiscoveredCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('confidence', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Уверенность')),
                ('source_kind', models.CharField(max_length=32, verbose_name='Откуда')),
                ('source_text', models.CharField(blank=True, default='', max_length=300, verbose_name='Фрагмент')),
                ('observed_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Определено')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seller_lead_category_links', to='core.partcategory', verbose_name='Категория')),
                ('seller_lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category_links', to='core.sellerlead', verbose_name='Найденный продавец')),
            ],
            options={
                'verbose_name': 'Найденная категория',
                'verbose_name_plural': 'Найденные категории',
            },
        ),
        migrations.AddField(
            model_name='sellerlead',
            name='discovered_categories',
            field=models.ManyToManyField(blank=True, related_name='discovered_seller_leads', through='core.SellerLeadDiscoveredCategory', to='core.partcategory', verbose_name='Найденные категории'),
        ),
        migrations.CreateModel(
            name='SellerLeadDiscoveredModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('confidence', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Уверенность')),
                ('source_kind', models.CharField(max_length=32, verbose_name='Откуда')),
                ('source_text', models.CharField(blank=True, default='', max_length=300, verbose_name='Фрагмент')),
                ('observed_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Определено')),
                ('car_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seller_lead_model_links', to='core.carmodel', verbose_name='Модель')),
                ('seller_lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='model_links', to='core.sellerlead', verbose_name='Найденный продавец')),
            ],
            options={
                'verbose_name': 'Найденная модель',
                'verbose_name_plural': 'Найденные модели',
            },
        ),
        migrations.AddField(
            model_name='sellerlead',
            name='discovered_models',
            field=models.ManyToManyField(blank=True, related_name='discovered_seller_leads', through='core.SellerLeadDiscoveredModel', to='core.carmodel', verbose_name='Найденные модели'),
        ),
        migrations.AddConstraint(
            model_name='sellerleaddiscoveredbrand',
            constraint=models.UniqueConstraint(fields=('seller_lead', 'brand'), name='unique_sellerlead_discovered_brand'),
        ),
        migrations.AddConstraint(
            model_name='sellerleaddiscoveredcategory',
            constraint=models.UniqueConstraint(fields=('seller_lead', 'category'), name='unique_sellerlead_discovered_category'),
        ),
        migrations.AddConstraint(
            model_name='sellerleaddiscoveredmodel',
            constraint=models.UniqueConstraint(fields=('seller_lead', 'car_model'), name='unique_sellerlead_discovered_model'),
        ),
    ]
