# Generated by Django 6.0.5 on 2026-10-03 13:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0049_seller_discovery_classification'),
    ]

    operations = [
        migrations.AddField(
            model_name='sellerlead',
            name='business_type_evidence_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='business_type_leads', to='core.sellerleadevidence', verbose_name='Evidence типа бизнеса'),
        ),
        migrations.AddField(
            model_name='sellerlead',
            name='business_type_source',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='business_type_leads', to='core.sellerleadsource', verbose_name='Источник типа бизнеса'),
        ),
        migrations.AddField(
            model_name='sellerleaddiscoveredbrand',
            name='evidence',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='discovered_brand_links', to='core.sellerleadevidence', verbose_name='Evidence'),
        ),
        migrations.AddField(
            model_name='sellerleaddiscoveredbrand',
            name='source',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='discovered_brand_links', to='core.sellerleadsource', verbose_name='Источник'),
        ),
        migrations.AddField(
            model_name='sellerleaddiscoveredcategory',
            name='evidence',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='discovered_category_links', to='core.sellerleadevidence', verbose_name='Evidence'),
        ),
        migrations.AddField(
            model_name='sellerleaddiscoveredcategory',
            name='source',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='discovered_category_links', to='core.sellerleadsource', verbose_name='Источник'),
        ),
        migrations.AddField(
            model_name='sellerleaddiscoveredmodel',
            name='evidence',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='discovered_model_links', to='core.sellerleadevidence', verbose_name='Evidence'),
        ),
        migrations.AddField(
            model_name='sellerleaddiscoveredmodel',
            name='source',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='discovered_model_links', to='core.sellerleadsource', verbose_name='Источник'),
        ),
    ]
