# Generated by Django 6.0.5 on 2026-10-04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0050_seller_discovery_classification_provenance'),
    ]

    operations = [
        migrations.AddField(
            model_name='sellerlead',
            name='last_enrichment_attempt_at',
            field=models.DateTimeField(
                blank=True,
                db_index=True,
                null=True,
                verbose_name='Последняя попытка обогащения',
            ),
        ),
    ]
