# Generated by Django 6.0.5

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0051_sellerlead_last_enrichment_attempt_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='sellerlead',
            name='market_scope',
            field=models.CharField(
                choices=[
                    ('kz', 'Казахстан'),
                    ('foreign', 'Зарубежный'),
                    ('unknown', 'Рынок не определён'),
                ],
                db_index=True,
                default='unknown',
                max_length=16,
                verbose_name='Рынок',
            ),
        ),
        migrations.AddField(
            model_name='sellerlead',
            name='market_scope_evidence',
            field=models.CharField(
                blank=True,
                default='',
                max_length=300,
                verbose_name='Основание рынка',
            ),
        ),
        migrations.AddField(
            model_name='sellerlead',
            name='next_enrichment_at',
            field=models.DateTimeField(
                blank=True,
                db_index=True,
                null=True,
                verbose_name='Следующее обогащение',
            ),
        ),
        migrations.AddField(
            model_name='sellerlead',
            name='enrichment_attempt_count',
            field=models.PositiveIntegerField(
                default=0,
                verbose_name='Завершённые проходы без WhatsApp',
            ),
        ),
        migrations.AddField(
            model_name='sellerlead',
            name='last_enrichment_result',
            field=models.CharField(
                blank=True,
                default='',
                max_length=32,
                verbose_name='Результат последнего обогащения',
            ),
        ),
        migrations.AlterField(
            model_name='sellerlead',
            name='business_type',
            field=models.CharField(
                choices=[
                    ('new_parts', 'Магазин запчастей'),
                    ('dismantler', 'Авторазбор'),
                    ('wholesaler', 'Оптовый поставщик'),
                    ('dealer', 'Дилер'),
                    ('service_parts', 'СТО с запчастями'),
                    ('service_only', 'Сервис без продажи запчастей'),
                    ('other_auto', 'Автобизнес, тип неясен'),
                    ('mixed', 'Смешанный профиль'),
                    ('unknown', 'Не определено'),
                ],
                db_index=True,
                default='unknown',
                max_length=16,
                verbose_name='Тип бизнеса',
            ),
        ),
    ]
