# Generated by Django 6.0.5 on 2026-10-05 09:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0052_sellerlead_market_and_enrichment_schedule'),
    ]

    operations = [
        migrations.AddField(
            model_name='instagrampublication',
            name='next_attempt_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Следующая попытка не раньше'),
        ),
        migrations.AddField(
            model_name='instagrampublication',
            name='placement',
            field=models.CharField(choices=[('story', 'Сторис'), ('feed', 'Лента')], db_index=True, default='story', max_length=16, verbose_name='Размещение'),
        ),
        migrations.AlterField(
            model_name='instagrampublication',
            name='request',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='instagram_publications', to='core.request', verbose_name='Заявка'),
        ),
        migrations.AlterField(
            model_name='instagrampublication',
            name='status',
            field=models.CharField(choices=[('draft', 'Черновик'), ('approved', 'Одобрено'), ('queued', 'В очереди'), ('publishing', 'Публикуется'), ('published', 'Опубликовано'), ('failed', 'Ошибка'), ('cancelled', 'Отменено'), ('needs_review', 'Нужно разобрать')], default='draft', max_length=20, verbose_name='Статус'),
        ),
        migrations.AddConstraint(
            model_name='instagrampublication',
            constraint=models.UniqueConstraint(fields=('request', 'placement'), name='uniq_instagram_publication_request_placement'),
        ),
    ]
