AUDIENCE_ACTIVITY_LAST_7_DAYS = 'last_7_days'
AUDIENCE_ACTIVITY_LAST_30_DAYS = 'last_30_days'
AUDIENCE_ACTIVITY_LAST_60_DAYS = 'last_60_days'
AUDIENCE_ACTIVITY_LAST_90_DAYS = 'last_90_days'
AUDIENCE_ACTIVITY_LAST_180_DAYS = 'last_180_days'
AUDIENCE_ACTIVITY_LAST_365_DAYS = 'last_365_days'
AUDIENCE_ACTIVITY_OLDER_THAN_180_DAYS = 'older_than_180_days'
AUDIENCE_ACTIVITY_NO_ACTIVITY_DATE = 'no_activity_date'

AUDIENCE_ACTIVITY_PERIODS = {
    AUDIENCE_ACTIVITY_LAST_7_DAYS,
    AUDIENCE_ACTIVITY_LAST_30_DAYS,
    AUDIENCE_ACTIVITY_LAST_60_DAYS,
    AUDIENCE_ACTIVITY_LAST_90_DAYS,
    AUDIENCE_ACTIVITY_LAST_180_DAYS,
    AUDIENCE_ACTIVITY_LAST_365_DAYS,
    AUDIENCE_ACTIVITY_OLDER_THAN_180_DAYS,
    AUDIENCE_ACTIVITY_NO_ACTIVITY_DATE,
}

AUDIENCE_ACTIVITY_DAYS = {
    AUDIENCE_ACTIVITY_LAST_7_DAYS: 7,
    AUDIENCE_ACTIVITY_LAST_30_DAYS: 30,
    AUDIENCE_ACTIVITY_LAST_60_DAYS: 60,
    AUDIENCE_ACTIVITY_LAST_90_DAYS: 90,
    AUDIENCE_ACTIVITY_LAST_180_DAYS: 180,
    AUDIENCE_ACTIVITY_LAST_365_DAYS: 365,
}
