"""
Оркестрация безопасной публикации заявок в Instagram Stories.
"""

from __future__ import annotations

import logging
from datetime import timedelta
from pathlib import Path

import requests
from django.conf import settings
from django.db import IntegrityError
from django.db.models import Count
from django.utils import timezone

from catalog.image_generator import (
    InstagramStoryGenerationError,
    build_publication_caption,
    generate_instagram_story,
)
from catalog.instagram_api import (
    InstagramPublishError,
    InstagramTemporaryImageUrlError,
    absolute_media_path_to_relative,
    publish_story_to_instagram,
)
from core.instagram_sanitize import is_junk_only_description
from core.models import InstagramPublication, Request

logger = logging.getLogger(__name__)

STUCK_PUBLISHING_TIMEOUT = timedelta(minutes=5)
MAX_IMAGE_URL_RETRIES = 3
MISSING_CRON_IMAGE_MESSAGE = (
    'Instagram publication image is missing before cron publish.'
)


def get_instagram_publish_mode() -> str:
    mode = (getattr(settings, 'INSTAGRAM_PUBLISH_MODE', 'OFF') or 'OFF').strip().upper()
    if mode not in ('OFF', 'TEST', 'LIVE'):
        logger.warning('Неизвестный INSTAGRAM_PUBLISH_MODE=%s, используется OFF.', mode)
        return 'OFF'
    return mode


def schedule_instagram_publication_for_request(request_id: int) -> None:
    """Prepare an Instagram publication after the Request is committed.

    Render cron filesystem is isolated from backend persistent MEDIA_ROOT.
    Therefore production story images must be generated by the backend before queueing.
    Meta API stays in the cron/management command.
    """
    try:
        prepare_instagram_publication_for_request(request_id)
    except Exception:
        logger.exception(
            'Instagram pipeline failed for request #%s',
            request_id,
        )


def prepare_instagram_publication_for_request(
    request_id: int,
) -> InstagramPublication | None:
    """Create the publication, store the story JPEG in MEDIA_ROOT, then queue.

    A buyer request must still succeed when image generation fails.
    """
    return enqueue_instagram_publication_for_request(request_id)


def enqueue_instagram_publication_for_request(
    request_id: int,
) -> InstagramPublication | None:
    """Create or reuse a publication without calling Meta API.

    LIVE mode stores the story JPEG in this process's MEDIA_ROOT before QUEUED.
    OFF creates nothing. TEST keeps a draft and does not generate an image.
    """
    mode = get_instagram_publish_mode()
    if mode == 'OFF':
        logger.debug('Instagram publish mode OFF — пропуск заявки #%s', request_id)
        return None

    existing = InstagramPublication.objects.filter(request_id=request_id).first()
    if existing:
        logger.info(
            'Instagram publication already exists for request #%s (status=%s)',
            request_id,
            existing.status,
        )
        if mode == 'LIVE' and existing.status in (
            InstagramPublication.STATUS_DRAFT,
            InstagramPublication.STATUS_FAILED,
        ):
            return _queue_live_publication_with_backend_image(existing)
        return existing

    try:
        product_request = Request.objects.get(pk=request_id)
    except Request.DoesNotExist:
        logger.warning('Request #%s not found for Instagram publication', request_id)
        return None

    junk_only_description = is_junk_only_description(product_request.description)
    caption = build_publication_caption(product_request)
    if junk_only_description:
        logger.info(
            'Request #%s has junk-only description, Instagram publication will stay draft',
            request_id,
        )

    try:
        publication = InstagramPublication.objects.create(
            request=product_request,
            caption=caption,
            status=InstagramPublication.STATUS_DRAFT,
        )
    except IntegrityError:
        logger.info('Instagram publication race for request #%s', request_id)
        return InstagramPublication.objects.filter(request_id=request_id).first()

    logger.info(
        'Instagram publication created for request #%s (publication #%s, status=%s)',
        request_id,
        publication.pk,
        publication.status,
    )
    if mode == 'LIVE' and not junk_only_description:
        return _queue_live_publication_with_backend_image(publication)
    return publication


def _queue_live_publication_with_backend_image(
    publication: InstagramPublication,
) -> InstagramPublication:
    try:
        product_request = publication.request
    except Request.DoesNotExist:
        return _mark_publication_failed(
            publication,
            'Заявка для Instagram-публикации не найдена.',
        )
    if is_junk_only_description(product_request.description):
        return publication
    if not publication.image:
        publication = ensure_instagram_story_image(publication)
        publication.refresh_from_db()
    if publication.status == InstagramPublication.STATUS_FAILED or not publication.image:
        return publication
    if not _story_file_exists(publication):
        return _mark_publication_failed(
            publication,
            'Instagram Story file was not saved to media storage.',
        )
    return queue_instagram_publication_for_processing(publication)


def _story_file_exists(publication: InstagramPublication) -> bool:
    if not publication.image:
        return False
    return (Path(settings.MEDIA_ROOT) / publication.image.name).is_file()


def ensure_instagram_story_image(
    publication: InstagramPublication,
) -> InstagramPublication:
    """Generate and attach a story image in this process's MEDIA_ROOT.

    Render cron filesystem is isolated from backend persistent MEDIA_ROOT.
    Therefore production story images must be generated by the backend before queueing.
    """
    if publication.image and _story_file_exists(publication):
        return publication

    try:
        product_request = publication.request
    except Request.DoesNotExist:
        return _mark_publication_failed(
            publication,
            'Заявка для Instagram-публикации не найдена.',
        )

    try:
        output_path, caption = generate_instagram_story(product_request)
    except InstagramStoryGenerationError as exc:
        logger.warning(
            'Instagram Story not generated for publication #%s request #%s: %s',
            publication.pk,
            publication.request_id,
            exc,
        )
        return _mark_publication_failed(publication, str(exc))
    except Exception as exc:
        logger.exception(
            'Instagram Story generation failed for publication #%s request #%s',
            publication.pk,
            publication.request_id,
        )
        return _mark_publication_failed(
            publication,
            f'Не удалось подготовить Instagram Story: {exc}',
        )

    try:
        relative_path = absolute_media_path_to_relative(output_path)
    except Exception as exc:
        logger.exception(
            'Instagram Story path is outside MEDIA_ROOT for publication #%s',
            publication.pk,
        )
        return _mark_publication_failed(
            publication,
            f'Не удалось сохранить Instagram Story в media storage: {exc}',
        )

    media_file = Path(settings.MEDIA_ROOT) / relative_path
    file_exists = media_file.is_file()
    logger.info(
        'Instagram story generated request #%s publication #%s image=%s file_exists=%s',
        publication.request_id,
        publication.pk,
        relative_path,
        file_exists,
    )
    if not file_exists:
        return _mark_publication_failed(
            publication,
            'Instagram Story file was not saved to media storage.',
        )

    publication.image.name = relative_path
    update_fields = ['image']
    if caption and not publication.caption:
        publication.caption = caption
        update_fields.append('caption')
    publication.status = InstagramPublication.STATUS_DRAFT
    publication.error_message = ''
    update_fields.extend(['status', 'error_message'])
    publication.save(update_fields=update_fields)
    return publication


def process_instagram_publication_for_request(request_id: int) -> InstagramPublication | None:
    mode = get_instagram_publish_mode()
    if mode == 'OFF':
        logger.debug('Instagram publish mode OFF — пропуск заявки #%s', request_id)
        return None

    existing = InstagramPublication.objects.filter(request_id=request_id).first()
    if existing:
        logger.info(
            'Instagram publication already exists for request #%s (status=%s)',
            request_id,
            existing.status,
        )
        if not existing.image:
            existing = ensure_instagram_story_image(existing)
            existing.refresh_from_db()
            if not existing.image:
                return existing
        if mode == 'LIVE' and existing.status in (
            InstagramPublication.STATUS_DRAFT,
            InstagramPublication.STATUS_FAILED,
        ):
            try:
                product_request = Request.objects.get(pk=request_id)
            except Request.DoesNotExist:
                return existing
            if not is_junk_only_description(product_request.description):
                queue_instagram_publication_for_processing(existing)
            return existing
        return existing

    try:
        product_request = Request.objects.get(pk=request_id)
    except Request.DoesNotExist:
        logger.warning('Request #%s not found for Instagram publication', request_id)
        return None

    junk_only_description = is_junk_only_description(product_request.description)
    if junk_only_description:
        logger.info(
            'Request #%s has junk-only description, Instagram publication will stay draft',
            request_id,
        )

    try:
        output_path, caption = generate_instagram_story(product_request)
    except InstagramStoryGenerationError as exc:
        logger.warning(
            'Instagram Story not generated for request #%s: %s',
            request_id,
            exc,
        )
        return None

    relative_path = absolute_media_path_to_relative(output_path)

    try:
        publication = InstagramPublication.objects.create(
            request=product_request,
            caption=caption,
            status=InstagramPublication.STATUS_DRAFT,
        )
    except IntegrityError:
        logger.info('Instagram publication race for request #%s', request_id)
        publication = InstagramPublication.objects.get(request_id=request_id)
        if not publication.image:
            publication = ensure_instagram_story_image(publication)
        return publication

    publication.image.name = relative_path
    publication.save(update_fields=['image'])

    logger.info(
        'Instagram draft created for request #%s (publication #%s)',
        request_id,
        publication.pk,
    )

    if mode == 'LIVE' and not junk_only_description:
        queue_instagram_publication_for_processing(publication)
        return publication

    return publication


def queue_instagram_publication_for_processing(
    publication: InstagramPublication,
) -> InstagramPublication:
    """Ставит публикацию в очередь без синхронного вызова Meta API."""
    if publication.status == InstagramPublication.STATUS_PUBLISHED:
        return publication

    publication.status = InstagramPublication.STATUS_QUEUED
    publication.publishing_started_at = None
    publication.error_message = ''
    publication.retry_count = 0
    publication.last_attempt_at = None
    publication.save(
        update_fields=[
            'status',
            'publishing_started_at',
            'error_message',
            'retry_count',
            'last_attempt_at',
        ]
    )
    logger.info(
        'Instagram publication #%s request #%s queued image=%s file_exists=%s',
        publication.pk,
        publication.request_id,
        publication.image.name,
        _story_file_exists(publication),
    )
    return publication


def get_instagram_publication_queue_diagnostics() -> dict:
    """Диагностика очереди Instagram-публикаций для cron / management-команды."""
    total = InstagramPublication.objects.count()
    status_counts = {
        status_value: 0
        for status_value, _label in InstagramPublication.STATUS_CHOICES
    }
    for row in InstagramPublication.objects.values('status').annotate(
        count=Count('id'),
    ):
        status_counts[row['status']] = row['count']

    recent = list(
        InstagramPublication.objects.order_by('-created_at').values(
            'id',
            'status',
            'created_at',
        )[:5]
    )
    return {
        'total': total,
        'by_status': status_counts,
        'recent': recent,
    }


def process_queued_instagram_publications() -> dict[str, int]:
    """
    Обрабатывает очередь queued-публикаций (для management-команды / cron).

    :returns: счётчики processed, published, failed, stuck_reset.
    """
    stats = {
        'processed': 0,
        'published': 0,
        'failed': 0,
        'stuck_reset': 0,
    }

    stuck_publications = InstagramPublication.objects.filter(
        status=InstagramPublication.STATUS_PUBLISHING,
    )
    for publication in stuck_publications:
        before_status = publication.status
        mark_stuck_instagram_publication_failed(publication)
        publication.refresh_from_db()
        if publication.status == InstagramPublication.STATUS_FAILED and before_status != publication.status:
            stats['stuck_reset'] += 1

    queued_publications = list(
        InstagramPublication.objects.filter(
            status=InstagramPublication.STATUS_QUEUED,
        ).order_by('created_at')
    )

    for publication in queued_publications:
        stats['processed'] += 1
        before_status = publication.status
        publish_instagram_publication(
            publication,
            validate_image_url=True,
            source='management',
        )
        publication.refresh_from_db()
        if publication.status == InstagramPublication.STATUS_PUBLISHED:
            stats['published'] += 1
        elif (
            publication.status == InstagramPublication.STATUS_FAILED
            and before_status != publication.status
        ):
            stats['failed'] += 1

    return stats


def is_publication_stuck_publishing(publication: InstagramPublication) -> bool:
    if publication.status != InstagramPublication.STATUS_PUBLISHING:
        return False
    started_at = publication.publishing_started_at
    if started_at is None:
        return False
    return timezone.now() - started_at >= STUCK_PUBLISHING_TIMEOUT


def mark_stuck_instagram_publication_failed(
    publication: InstagramPublication,
    *,
    message: str = 'Публикация зависла в статусе «Публикуется» более 5 минут.',
) -> InstagramPublication:
    if publication.status != InstagramPublication.STATUS_PUBLISHING:
        return publication
    if not is_publication_stuck_publishing(publication):
        return publication
    publication.status = InstagramPublication.STATUS_FAILED
    publication.error_message = message
    publication.publishing_started_at = None
    publication.save(update_fields=['status', 'error_message', 'publishing_started_at'])
    logger.warning(
        'Instagram publication #%s marked failed after stuck publishing',
        publication.pk,
    )
    return publication


def _mark_publication_failed(
    publication: InstagramPublication,
    message: str,
) -> InstagramPublication:
    publication.status = InstagramPublication.STATUS_FAILED
    publication.error_message = message
    publication.publishing_started_at = None
    publication.last_attempt_at = timezone.now()
    publication.save(
        update_fields=[
            'status',
            'error_message',
            'publishing_started_at',
            'last_attempt_at',
        ]
    )
    return publication


def _requeue_publication_for_temporary_image_url_error(
    publication: InstagramPublication,
    *,
    status_code: int,
) -> InstagramPublication:
    new_retry_count = publication.retry_count + 1
    now = timezone.now()

    if new_retry_count >= MAX_IMAGE_URL_RETRIES:
        publication.status = InstagramPublication.STATUS_FAILED
        publication.error_message = (
            f'Временная недоступность image_url: HTTP {status_code}. '
            f'Превышено число попыток ({MAX_IMAGE_URL_RETRIES}).'
        )
        logger.warning(
            'Instagram publication #%s: temporary image_url error HTTP %s, failed after %s attempts',
            publication.pk,
            status_code,
            new_retry_count,
        )
    else:
        publication.status = InstagramPublication.STATUS_QUEUED
        publication.error_message = (
            f'Временная недоступность image_url: HTTP {status_code}. '
            'Будет повторено позже.'
        )
        logger.warning(
            'Instagram publication #%s: temporary image_url error HTTP %s, requeued',
            publication.pk,
            status_code,
        )

    publication.retry_count = new_retry_count
    publication.last_attempt_at = now
    publication.publishing_started_at = None
    publication.save(
        update_fields=[
            'status',
            'error_message',
            'retry_count',
            'last_attempt_at',
            'publishing_started_at',
        ]
    )
    return publication


def publish_instagram_publication(
    publication: InstagramPublication,
    *,
    validate_image_url: bool = False,
    source: str = 'direct',
) -> InstagramPublication:
    if publication.status == InstagramPublication.STATUS_PUBLISHED:
        logger.info(
            'Instagram publication #%s already published, skip',
            publication.pk,
        )
        return publication

    if publication.status == InstagramPublication.STATUS_CANCELLED:
        logger.info(
            'Instagram publication #%s cancelled, skip publish',
            publication.pk,
        )
        return publication

    if publication.status == InstagramPublication.STATUS_PUBLISHING:
        if is_publication_stuck_publishing(publication):
            logger.warning(
                'Instagram publication #%s stuck in publishing, waiting for reset',
                publication.pk,
            )
        else:
            logger.info(
                'Instagram publication #%s already publishing, skip',
                publication.pk,
            )
        return publication

    if publication.status not in (
        InstagramPublication.STATUS_QUEUED,
        InstagramPublication.STATUS_FAILED,
        InstagramPublication.STATUS_DRAFT,
    ):
        logger.info(
            'Instagram publication #%s status=%s, skip publish',
            publication.pk,
            publication.status,
        )
        return publication

    if not publication.image:
        logger.warning(
            'Instagram publication #%s request #%s has no image before publish source=%s',
            publication.pk,
            publication.request_id,
            source,
        )
        return _mark_publication_failed(publication, MISSING_CRON_IMAGE_MESSAGE)

    if source == 'management':
        logger.info(
            'Instagram cron publish started publication #%s request #%s image=%s',
            publication.pk,
            publication.request_id,
            publication.image.name,
        )
    else:
        logger.info(
            'Instagram publication #%s request #%s: начало публикации image=%s',
            publication.pk,
            publication.request_id,
            publication.image.name,
        )

    publication.status = InstagramPublication.STATUS_PUBLISHING
    publication.error_message = ''
    publication.publishing_started_at = timezone.now()
    publication.save(update_fields=['status', 'error_message', 'publishing_started_at'])

    try:
        result = publish_story_to_instagram(
            publication.image.name,
            publication_id=publication.pk,
            validate_image_url=validate_image_url,
        )
    except InstagramTemporaryImageUrlError as exc:
        return _requeue_publication_for_temporary_image_url_error(
            publication,
            status_code=exc.status_code,
        )
    except InstagramPublishError as exc:
        _mark_publication_failed(publication, str(exc))
        logger.warning(
            'Instagram publish failed for publication #%s: %s',
            publication.pk,
            exc,
        )
        return publication
    except requests.RequestException as exc:
        _mark_publication_failed(
            publication,
            f'Сетевая ошибка Meta API: {exc}',
        )
        logger.exception(
            'Instagram publish network error for publication #%s',
            publication.pk,
        )
        return publication
    except Exception as exc:
        _mark_publication_failed(publication, str(exc))
        logger.exception(
            'Unexpected Instagram publish error for publication #%s',
            publication.pk,
        )
        return publication

    publication.instagram_container_id = result.get('container_id', '')
    publication.instagram_media_id = result.get('media_id', '')
    publication.status = InstagramPublication.STATUS_PUBLISHED
    publication.published_at = timezone.now()
    publication.error_message = ''
    publication.publishing_started_at = None
    publication.retry_count = 0
    publication.last_attempt_at = timezone.now()
    publication.save(
        update_fields=[
            'instagram_container_id',
            'instagram_media_id',
            'status',
            'published_at',
            'error_message',
            'publishing_started_at',
            'retry_count',
            'last_attempt_at',
        ]
    )
    logger.info(
        'Instagram publication #%s published (media_id=%s)',
        publication.pk,
        publication.instagram_media_id,
    )
    return publication


def approve_instagram_publication(publication: InstagramPublication) -> InstagramPublication:
    if publication.status in (
        InstagramPublication.STATUS_DRAFT,
        InstagramPublication.STATUS_FAILED,
    ):
        publication.status = InstagramPublication.STATUS_APPROVED
        publication.error_message = ''
        publication.publishing_started_at = None
        publication.save(update_fields=['status', 'error_message', 'publishing_started_at'])
    return publication


def cancel_instagram_publication(publication: InstagramPublication) -> InstagramPublication:
    if publication.status == InstagramPublication.STATUS_PUBLISHED:
        return publication
    publication.status = InstagramPublication.STATUS_CANCELLED
    publication.save(update_fields=['status'])
    return publication
