# Generated by Django 6.0.5 on 2026-07-16 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MarketingCabinetPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Доступ к кабинету маркетинга',
                'verbose_name_plural': 'Доступ к кабинету маркетинга',
                'permissions': [('access_marketing_cabinet', 'Доступ к кабинету рассылок и уведомлений')],
            },
        ),
    ]
