# Generated by Django 6.0.5 on 2026-07-17 08:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MarketingAudience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название аудитории')),
                ('description', models.TextField(blank=True, default='', verbose_name='Описание')),
                ('contact_group', models.CharField(choices=[('buyers', 'Покупатели'), ('sellers', 'Продавцы'), ('service_providers', 'Исполнители услуг'), ('test_contacts', 'Тестовые контакты')], max_length=32, verbose_name='Группа контактов')),
                ('contact_subtype', models.CharField(max_length=32, verbose_name='Подтип')),
                ('criteria', models.JSONField(blank=True, default=dict, verbose_name='Критерии')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создана')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлена')),
                ('last_calculated_at', models.DateTimeField(blank=True, null=True, verbose_name='Последний расчёт')),
                ('last_matched_count', models.PositiveIntegerField(default=0, verbose_name='Найдено при последнем расчёте')),
                ('last_eligible_count', models.PositiveIntegerField(default=0, verbose_name='Допустимо при последнем расчёте')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='marketing_audiences', to=settings.AUTH_USER_MODEL, verbose_name='Автор')),
            ],
            options={
                'verbose_name': 'Аудитория маркетинга',
                'verbose_name_plural': 'Аудитории маркетинга',
                'ordering': ('-updated_at', '-id'),
                'constraints': [models.UniqueConstraint(fields=('name',), name='marketing_audience_unique_name')],
            },
        ),
    ]
