# Generated by Django 6.0.5 on 2026-07-17 11:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0002_marketingaudience'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MarketingCampaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название кампании')),
                ('description', models.TextField(blank=True, default='', verbose_name='Описание')),
                ('purpose', models.CharField(choices=[('parts_buyers', 'Покупатели запчастей'), ('marketplace_buyers', 'Покупатели маркетплейса'), ('service_customers', 'Заказчики услуг'), ('request_sellers', 'Продавцы по заявкам'), ('marketplace_sellers', 'Продавцы маркетплейса'), ('combined_sellers', 'Продавцы обоих направлений'), ('sto_providers', 'СТО'), ('detailing_providers', 'Детейлинг'), ('test_campaign', 'Тестовая кампания')], max_length=32, verbose_name='Назначение')),
                ('channel', models.CharField(choices=[('whatsapp', 'WhatsApp')], default='whatsapp', max_length=16, verbose_name='Канал')),
                ('status', models.CharField(choices=[('draft', 'Черновик'), ('audience_prepared', 'Получатели подготовлены'), ('audience_stale', 'Аудитория изменилась'), ('cancelled', 'Отменена'), ('archived', 'В архиве')], default='draft', max_length=32, verbose_name='Статус')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создана')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлена')),
                ('audience_prepared_at', models.DateTimeField(blank=True, null=True, verbose_name='Получатели подготовлены')),
                ('audience_updated_at_at_prepare', models.DateTimeField(blank=True, null=True, verbose_name='Версия аудитории при подготовке')),
                ('audience_signature_at_prepare', models.CharField(blank=True, default='', max_length=64, verbose_name='Сигнатура аудитории при подготовке')),
                ('matched_count', models.PositiveIntegerField(default=0, verbose_name='Найдено')),
                ('unique_count', models.PositiveIntegerField(default=0, verbose_name='Уникальных')),
                ('eligible_count', models.PositiveIntegerField(default=0, verbose_name='Допустимо')),
                ('excluded_count', models.PositiveIntegerField(default=0, verbose_name='Исключено')),
                ('test_count', models.PositiveIntegerField(default=0, verbose_name='Тестовых')),
                ('invalid_phone_count', models.PositiveIntegerField(default=0, verbose_name='Некорректных телефонов')),
                ('duplicate_count', models.PositiveIntegerField(default=0, verbose_name='Дубликатов')),
                ('inactive_count', models.PositiveIntegerField(default=0, verbose_name='Неактивных')),
                ('consent_granted_count', models.PositiveIntegerField(default=0, verbose_name='Согласие дано')),
                ('consent_unknown_count', models.PositiveIntegerField(default=0, verbose_name='Согласие не подтверждено')),
                ('consent_revoked_count', models.PositiveIntegerField(default=0, verbose_name='Согласие отозвано')),
                ('consent_not_recorded_count', models.PositiveIntegerField(default=0, verbose_name='Согласие не зафиксировано')),
                ('archived_at', models.DateTimeField(blank=True, null=True, verbose_name='Архивирована')),
                ('cancelled_at', models.DateTimeField(blank=True, null=True, verbose_name='Отменена')),
                ('audience', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='campaigns', to='marketing.marketingaudience', verbose_name='Аудитория')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='marketing_campaigns', to=settings.AUTH_USER_MODEL, verbose_name='Автор')),
            ],
            options={
                'verbose_name': 'Маркетинговая кампания',
                'verbose_name_plural': 'Маркетинговые кампании',
                'ordering': ('-created_at', '-id'),
            },
        ),
        migrations.CreateModel(
            name='MarketingCampaignRecipient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_normalized', models.CharField(max_length=32, verbose_name='Телефон (внутренний)')),
                ('display_name', models.CharField(default='—', max_length=255, verbose_name='Имя')),
                ('city', models.CharField(default='—', max_length=255, verbose_name='Город')),
                ('roles', models.JSONField(default=list, verbose_name='Роли')),
                ('vehicle_summary', models.CharField(default='—', max_length=255, verbose_name='Автомобиль')),
                ('last_activity_at', models.DateTimeField(blank=True, null=True, verbose_name='Активность')),
                ('is_test_contact', models.BooleanField(default=False, verbose_name='Тестовый контакт')),
                ('consent_status', models.CharField(default='', max_length=32, verbose_name='Согласие')),
                ('eligibility_status', models.CharField(choices=[('eligible', 'Допустим'), ('excluded', 'Исключён')], max_length=16, verbose_name='Статус')),
                ('exclusion_reason', models.CharField(blank=True, choices=[('', '—'), ('invalid_phone', 'Некорректный телефон'), ('duplicate', 'Дубликат'), ('test_contact', 'Тестовый контакт'), ('inactive', 'Неактивный'), ('consent_unknown', 'Согласие не подтверждено'), ('consent_revoked', 'Согласие отозвано'), ('consent_not_recorded', 'Рекламное согласие не зафиксировано'), ('audience_rule', 'Правило аудитории'), ('other', 'Другое')], default='', max_length=32, verbose_name='Причина исключения')),
                ('source_summary', models.JSONField(default=dict, verbose_name='Источник')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipients', to='marketing.marketingcampaign', verbose_name='Кампания')),
            ],
            options={
                'verbose_name': 'Получатель кампании',
                'verbose_name_plural': 'Получатели кампании',
                'ordering': ('-last_activity_at', 'id'),
            },
        ),
        migrations.AddConstraint(
            model_name='marketingcampaignrecipient',
            constraint=models.UniqueConstraint(fields=('campaign', 'phone_normalized'), name='marketing_campaign_recipient_unique_phone'),
        ),
    ]
