# Generated by Django 6.0.5 on 2026-07-21 05:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0003_marketingcampaign'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='marketingcampaign',
            name='template_selected_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Шаблон выбран'),
        ),
        migrations.CreateModel(
            name='MarketingWhatsAppTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Внутреннее название')),
                ('meta_template_name', models.CharField(max_length=150, verbose_name='Meta template name')),
                ('language_code', models.CharField(default='ru', max_length=20, verbose_name='Код языка')),
                ('category', models.CharField(default='marketing', max_length=32, verbose_name='Категория')),
                ('meta_status', models.CharField(choices=[('unknown', 'Неизвестен'), ('draft', 'Черновик'), ('pending', 'На проверке'), ('approved', 'Одобрен'), ('rejected', 'Отклонён'), ('paused', 'Приостановлен'), ('disabled', 'Отключён')], default='unknown', max_length=16, verbose_name='Статус в Meta (локально)')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('allowed_purposes', models.JSONField(blank=True, default=list, verbose_name='Разрешённые назначения кампаний')),
                ('allow_test_campaign', models.BooleanField(default=False, verbose_name='Разрешить тестовую кампанию')),
                ('header_text', models.TextField(blank=True, default='', verbose_name='Header')),
                ('body_text', models.TextField(blank=True, default='', verbose_name='Body')),
                ('footer_text', models.TextField(blank=True, default='', verbose_name='Footer')),
                ('buttons', models.JSONField(blank=True, default=list, verbose_name='Кнопки')),
                ('variables', models.JSONField(blank=True, default=list, verbose_name='Переменные')),
                ('internal_notes', models.TextField(blank=True, default='', verbose_name='Внутренние заметки')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлён')),
                ('last_status_checked_at', models.DateTimeField(blank=True, null=True, verbose_name='Последняя проверка статуса')),
                ('meta_template_id', models.CharField(blank=True, default='', max_length=64, verbose_name='Meta template ID')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='marketing_whatsapp_templates', to=settings.AUTH_USER_MODEL, verbose_name='Автор')),
            ],
            options={
                'verbose_name': 'Маркетинговый WhatsApp-шаблон',
                'verbose_name_plural': 'Маркетинговые WhatsApp-шаблоны',
                'ordering': ('-updated_at', '-id'),
            },
        ),
        migrations.AddField(
            model_name='marketingcampaign',
            name='message_template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='campaigns', to='marketing.marketingwhatsapptemplate', verbose_name='WhatsApp-шаблон'),
        ),
        migrations.AddConstraint(
            model_name='marketingwhatsapptemplate',
            constraint=models.UniqueConstraint(fields=('name',), name='marketing_whatsapp_template_unique_name'),
        ),
        migrations.AddConstraint(
            model_name='marketingwhatsapptemplate',
            constraint=models.UniqueConstraint(
                fields=('meta_template_name', 'language_code'),
                name='marketing_whatsapp_template_unique_meta_lang',
            ),
        ),
    ]
