# Generated by Django 6.0.5 on 2026-07-22 11:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0004_marketing_whatsapp_template'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MarketingCampaignSendRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mode', models.CharField(default='TEST', max_length=16, verbose_name='Режим')),
                ('status', models.CharField(choices=[('pending', 'Ожидает'), ('running', 'Отправка'), ('completed', 'Завершена'), ('completed_with_errors', 'Завершена с ошибками'), ('failed', 'Ошибка'), ('blocked', 'Заблокирована')], default='pending', max_length=32, verbose_name='Статус')),
                ('total_count', models.PositiveIntegerField(default=0, verbose_name='Всего')),
                ('sent_count', models.PositiveIntegerField(default=0, verbose_name='Отправлено')),
                ('failed_count', models.PositiveIntegerField(default=0, verbose_name='Ошибок')),
                ('skipped_count', models.PositiveIntegerField(default=0, verbose_name='Пропущено')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('started_at', models.DateTimeField(blank=True, null=True, verbose_name='Начат')),
                ('finished_at', models.DateTimeField(blank=True, null=True, verbose_name='Завершён')),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='send_runs', to='marketing.marketingcampaign', verbose_name='Кампания')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='marketing_campaign_send_runs', to=settings.AUTH_USER_MODEL, verbose_name='Инициатор')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='send_runs', to='marketing.marketingwhatsapptemplate', verbose_name='Шаблон')),
            ],
            options={
                'verbose_name': 'Запуск отправки кампании',
                'verbose_name_plural': 'Запуски отправки кампаний',
                'ordering': ('-created_at', '-id'),
            },
        ),
        migrations.CreateModel(
            name='MarketingCampaignMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_normalized', models.CharField(max_length=32, verbose_name='Телефон (snapshot)')),
                ('template_name', models.CharField(max_length=150, verbose_name='Meta template name')),
                ('language_code', models.CharField(max_length=20, verbose_name='Язык')),
                ('variables', models.JSONField(blank=True, default=dict, verbose_name='Переменные')),
                ('status', models.CharField(choices=[('pending', 'Ожидает'), ('sent', 'Отправлено'), ('failed', 'Ошибка'), ('skipped', 'Пропущено')], default='pending', max_length=16, verbose_name='Статус')),
                ('meta_message_id', models.CharField(blank=True, default='', max_length=128, verbose_name='Meta message ID')),
                ('error_code', models.CharField(blank=True, default='', max_length=64, verbose_name='Код ошибки')),
                ('error_message', models.TextField(blank=True, default='', verbose_name='Ошибка')),
                ('attempted_at', models.DateTimeField(blank=True, null=True, verbose_name='Попытка')),
                ('sent_at', models.DateTimeField(blank=True, null=True, verbose_name='Отправлено')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('campaign_recipient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='send_messages', to='marketing.marketingcampaignrecipient', verbose_name='Получатель снимка')),
                ('send_run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='marketing.marketingcampaignsendrun', verbose_name='Запуск')),
            ],
            options={
                'verbose_name': 'Сообщение кампании',
                'verbose_name_plural': 'Сообщения кампаний',
                'ordering': ('id',),
                'constraints': [models.UniqueConstraint(fields=('send_run', 'campaign_recipient'), name='marketing_campaign_message_unique_recipient_run')],
            },
        ),
    ]
