# Generated by Django 6.0.5 on 2026-07-23 10:38

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0007_protect_campaign_send_run_history'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='marketingcampaignsendrun',
            name='queued_count',
            field=models.PositiveIntegerField(default=0, verbose_name='В очереди'),
        ),
        migrations.AlterField(
            model_name='marketingcampaignmessage',
            name='status',
            field=models.CharField(choices=[('pending', 'Ожидает'), ('queued', 'В очереди'), ('processing', 'Обработка'), ('sent', 'Отправлено'), ('failed', 'Ошибка'), ('skipped', 'Пропущено'), ('cancelled', 'Отменено')], default='pending', max_length=16, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='marketingcampaignsendrun',
            name='status',
            field=models.CharField(choices=[('pending', 'Ожидает'), ('queued', 'В очереди'), ('running', 'Отправка'), ('completed', 'Завершена'), ('partial', 'Частично'), ('completed_with_errors', 'Завершена с ошибками'), ('failed', 'Ошибка'), ('blocked', 'Заблокирована'), ('cancelled', 'Отменена')], default='pending', max_length=32, verbose_name='Статус'),
        ),
        migrations.AddIndex(
            model_name='marketingcampaignmessage',
            index=models.Index(fields=['send_run', 'status'], name='marketing_msg_run_status'),
        ),
        migrations.AddIndex(
            model_name='marketingcampaignsendrun',
            index=models.Index(fields=['mode', 'status', '-created_at'], name='marketing_sendrun_mode_status'),
        ),
        migrations.AddConstraint(
            model_name='marketingcampaignsendrun',
            constraint=models.UniqueConstraint(
                condition=models.Q(
                    ('mode', 'LIVE'),
                    ('status__in', ['queued', 'running']),
                ),
                fields=('campaign',),
                name='uniq_active_live_run_per_campaign',
            ),
        ),
    ]
