# Generated by Django 6.0.5 on 2026-08-31 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0016_ag_parts_all_sellers_audience'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marketingcampaign',
            name='purpose',
            field=models.CharField(choices=[('parts_buyers', 'Покупатели запчастей'), ('marketplace_buyers', 'Покупатели маркетплейса'), ('service_customers', 'Заказчики услуг'), ('request_sellers', 'Продавцы по заявкам'), ('marketplace_sellers', 'Продавцы маркетплейса'), ('combined_sellers', 'Продавцы обоих направлений'), ('all_sellers', 'Все продавцы запчастей'), ('sto_providers', 'СТО'), ('detailing_providers', 'Детейлинг'), ('test_campaign', 'Тестовая кампания')], max_length=32, verbose_name='Назначение'),
        ),
    ]
