from __future__ import annotations

SEND_MODE_TEST = 'TEST'
SEND_MODE_LIVE = 'LIVE'

SEND_RUN_STATUS_PENDING = 'pending'
SEND_RUN_STATUS_QUEUED = 'queued'
SEND_RUN_STATUS_RUNNING = 'running'
SEND_RUN_STATUS_COMPLETED = 'completed'
SEND_RUN_STATUS_PARTIAL = 'partial'
SEND_RUN_STATUS_COMPLETED_WITH_ERRORS = 'completed_with_errors'
SEND_RUN_STATUS_FAILED = 'failed'
SEND_RUN_STATUS_BLOCKED = 'blocked'
SEND_RUN_STATUS_CANCELLED = 'cancelled'

SEND_RUN_STATUS_CHOICES = (
    (SEND_RUN_STATUS_PENDING, 'Ожидает'),
    (SEND_RUN_STATUS_QUEUED, 'В очереди'),
    (SEND_RUN_STATUS_RUNNING, 'Отправка'),
    (SEND_RUN_STATUS_COMPLETED, 'Завершена'),
    (SEND_RUN_STATUS_PARTIAL, 'Частично'),
    (SEND_RUN_STATUS_COMPLETED_WITH_ERRORS, 'Завершена с ошибками'),
    (SEND_RUN_STATUS_FAILED, 'Ошибка'),
    (SEND_RUN_STATUS_BLOCKED, 'Заблокирована'),
    (SEND_RUN_STATUS_CANCELLED, 'Отменена'),
)

SEND_RUN_TERMINAL_STATUSES = frozenset({
    SEND_RUN_STATUS_COMPLETED,
    SEND_RUN_STATUS_PARTIAL,
    SEND_RUN_STATUS_COMPLETED_WITH_ERRORS,
    SEND_RUN_STATUS_FAILED,
    SEND_RUN_STATUS_BLOCKED,
    SEND_RUN_STATUS_CANCELLED,
})

SEND_RUN_LIVE_ACTIVE_STATUSES = frozenset({
    SEND_RUN_STATUS_QUEUED,
    SEND_RUN_STATUS_RUNNING,
})

SEND_RUN_LIVE_LAUNCH_BLOCK_STATUSES = frozenset({
    SEND_RUN_STATUS_QUEUED,
    SEND_RUN_STATUS_RUNNING,
    SEND_RUN_STATUS_COMPLETED,
    SEND_RUN_STATUS_PARTIAL,
    SEND_RUN_STATUS_COMPLETED_WITH_ERRORS,
})

MESSAGE_STATUS_PENDING = 'pending'
MESSAGE_STATUS_QUEUED = 'queued'
MESSAGE_STATUS_PROCESSING = 'processing'
MESSAGE_STATUS_SENT = 'sent'
MESSAGE_STATUS_FAILED = 'failed'
MESSAGE_STATUS_SKIPPED = 'skipped'
MESSAGE_STATUS_CANCELLED = 'cancelled'

MESSAGE_STATUS_CHOICES = (
    (MESSAGE_STATUS_PENDING, 'Ожидает'),
    (MESSAGE_STATUS_QUEUED, 'В очереди'),
    (MESSAGE_STATUS_PROCESSING, 'Обработка'),
    (MESSAGE_STATUS_SENT, 'Отправлено'),
    (MESSAGE_STATUS_FAILED, 'Ошибка'),
    (MESSAGE_STATUS_SKIPPED, 'Пропущено'),
    (MESSAGE_STATUS_CANCELLED, 'Отменено'),
)

MESSAGE_STATUS_LIVE_IN_FLIGHT = frozenset({
    MESSAGE_STATUS_QUEUED,
    MESSAGE_STATUS_PROCESSING,
})

MESSAGE_STATUS_LIVE_DELIVERED = frozenset({
    MESSAGE_STATUS_SENT,
})

ERROR_CODE_DELIVERY_UNKNOWN = 'delivery_unknown'
ERROR_CODE_CONSENT_REVOKED = 'consent_revoked'
ERROR_CODE_CONSENT_NOT_GRANTED = 'consent_not_granted'

VARIABLE_KEY_REQUEST_HISTORY_URL = 'request_history_url'

FORBIDDEN_SAMPLE_ACCESS_TOKEN = '11111111-1111-4111-8111-111111111111'
