# Generated by Django 6.0.4 on 2026-05-19 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_alter_brand_options_alter_carmodel_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sellerprofile',
            name='description',
            field=models.TextField(blank=True, default='', verbose_name='Описание маркета'),
        ),
        migrations.AddField(
            model_name='sellerprofile',
            name='instagram',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Instagram'),
        ),
        migrations.AddField(
            model_name='sellerprofile',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='seller_logos/', verbose_name='Логотип маркета'),
        ),
        migrations.AddField(
            model_name='sellerprofile',
            name='website',
            field=models.URLField(blank=True, default='', verbose_name='Сайт'),
        ),
    ]
