# Generated by Django 6.0.4 on 2026-05-22 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0007_sellerprofile_description_sellerprofile_instagram_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='selected_brands',
            field=models.ManyToManyField(blank=True, related_name='multi_products', to='catalog.brand', verbose_name='Марки товара'),
        ),
        migrations.AddField(
            model_name='product',
            name='selected_models',
            field=models.ManyToManyField(blank=True, related_name='multi_products', to='catalog.carmodel', verbose_name='Модели товара'),
        ),
    ]
