# Generated by Django 6.0.5 on 2026-06-14 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0008_product_selected_brands_product_selected_models'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='slug',
            field=models.SlugField(blank=True, default='', max_length=255, verbose_name='SEO ссылка'),
        ),
    ]
