# Generated by Django 6.0.5 on 2026-06-26 05:18

from django.db import migrations, models
from django.utils.text import slugify


def populate_seller_slugs(apps, schema_editor):
    SellerProfile = apps.get_model('catalog', 'SellerProfile')

    for seller in SellerProfile.objects.all():
        if seller.slug:
            continue

        base_slug = slugify(seller.name, allow_unicode=True) or 'seller'
        slug = base_slug
        counter = 1

        while SellerProfile.objects.filter(slug=slug).exclude(pk=seller.pk).exists():
            counter += 1
            slug = f'{base_slug}-{counter}'

        seller.slug = slug
        seller.save(update_fields=['slug'])


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0009_product_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='sellerprofile',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, null=True, unique=True, verbose_name='URL-адрес магазина'),
        ),
        migrations.RunPython(
            populate_seller_slugs,
            migrations.RunPython.noop,
        ),
    ]
