# Generated by Django 6.0.5 on 2026-06-26 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0010_sellerprofile_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='sellerprofile',
            name='address',
            field=models.CharField(blank=True, default='', max_length=500, verbose_name='Адрес склада'),
        ),
        migrations.AddField(
            model_name='sellerprofile',
            name='delivery_info',
            field=models.TextField(blank=True, default='', verbose_name='Доставка и оплата'),
        ),
        migrations.AddField(
            model_name='sellerprofile',
            name='work_hours',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='График работы'),
        ),
    ]
