# Generated by Django 6.0.5 on 2026-06-30 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0011_sellerprofile_b2b_contacts'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='supplier',
            field=models.CharField(
                choices=[
                    ('local', 'Локальный склад'),
                    ('phaeton', 'Phaeton (внешний API)'),
                ],
                db_index=True,
                default='local',
                max_length=32,
                verbose_name='Поставщик',
            ),
        ),
    ]
