# Generated by Django 6.0.5 on 2026-06-30

from django.db import migrations, models


def drop_legacy_unique_constraint(apps, schema_editor):
    vendor = schema_editor.connection.vendor

    if vendor == 'postgresql':
        schema_editor.execute(
            'ALTER TABLE catalog_product '
            'DROP CONSTRAINT IF EXISTS unique_product_article_brand_supplier'
        )
        return

    if vendor == 'sqlite':
        with schema_editor.connection.cursor() as cursor:
            cursor.execute(
                "SELECT name FROM sqlite_master "
                "WHERE type='index' AND name='unique_product_article_brand_supplier'"
            )
            if cursor.fetchone():
                schema_editor.execute(
                    'DROP INDEX unique_product_article_brand_supplier'
                )


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0012_product_supplier_and_more'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunPython(
                    drop_legacy_unique_constraint,
                    migrations.RunPython.noop,
                ),
            ],
            state_operations=[
                migrations.RemoveConstraint(
                    model_name='product',
                    name='unique_product_article_brand_supplier',
                ),
            ],
        ),
        migrations.AlterField(
            model_name='product',
            name='article',
            field=models.CharField(
                blank=True,
                db_index=True,
                default='',
                max_length=100,
                verbose_name='Артикул',
            ),
        ),
        migrations.AlterField(
            model_name='product',
            name='supplier',
            field=models.CharField(
                choices=[
                    ('local', 'Локальный склад'),
                    ('phaeton', 'Phaeton (внешний API)'),
                ],
                db_index=True,
                default='local',
                max_length=32,
                verbose_name='Поставщик',
            ),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(
                fields=['article', 'brand', 'supplier'],
                name='cat_prod_lookup_idx',
            ),
        ),
    ]
