# Generated by Django 6.0.5 on 2026-07-06 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0013_product_lookup_indexes'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='price_on_request',
            field=models.BooleanField(default=False, verbose_name='Цена по запросу'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Цена'),
        ),
    ]
