# Generated by Django 6.0.5 on 2026-08-24 11:11

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0016_sellerprofile_pickup_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductConsignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enabled', models.BooleanField(default=False, verbose_name='Доступно на реализацию')),
                ('max_qty', models.PositiveIntegerField(default=0, verbose_name='Максимальное количество')),
                ('settlement_price', models.PositiveIntegerField(default=0, verbose_name='Расчётная цена, ₸')),
                ('term_days', models.PositiveIntegerField(default=0, verbose_name='Срок реализации, дней')),
                ('conditions', models.TextField(blank=True, default='', verbose_name='Дополнительные условия')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
            ],
            options={
                'verbose_name': 'Реализация',
                'verbose_name_plural': 'Реализация',
            },
        ),
        migrations.CreateModel(
            name='ProductPriceTier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min_qty', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='От количества, шт.')),
                ('price', models.PositiveIntegerField(verbose_name='Цена за единицу, ₸')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
            ],
            options={
                'verbose_name': 'Оптовая цена',
                'verbose_name_plural': 'Оптовые цены',
                'ordering': ['min_qty', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ProductPromotion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('promotion_type', models.CharField(choices=[('sale', 'Распродажа'), ('promo', 'Акция')], max_length=16, verbose_name='Тип')),
                ('price', models.PositiveIntegerField(verbose_name='Специальная цена, ₸')),
                ('starts_at', models.DateTimeField(blank=True, null=True, verbose_name='Начало')),
                ('ends_at', models.DateTimeField(blank=True, null=True, verbose_name='Окончание')),
                ('qty_limit', models.PositiveIntegerField(blank=True, null=True, verbose_name='Лимит количества')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
            ],
            options={
                'verbose_name': 'Акция / распродажа',
                'verbose_name_plural': 'Акции и распродажи',
                'ordering': ['-starts_at', '-id'],
            },
        ),
        migrations.AlterModelOptions(
            name='productimage',
            options={'ordering': ['sort_order', 'id'], 'verbose_name': 'Фото товара', 'verbose_name_plural': 'Фото товаров'},
        ),
        migrations.AddField(
            model_name='product',
            name='cost_price',
            field=models.PositiveIntegerField(blank=True, help_text='Только для внутреннего учёта. Не показывается на сайте.', null=True, verbose_name='Себестоимость'),
        ),
        migrations.AddField(
            model_name='product',
            name='seller_profile',
            field=models.ForeignKey(blank=True, help_text='Явная привязка к кабинету продавца. Старые товары можно не заполнять.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_products', to='catalog.sellerprofile', verbose_name='Профиль продавца'),
        ),
        migrations.AddField(
            model_name='product',
            name='stock_qty',
            field=models.PositiveIntegerField(blank=True, help_text='Пустое значение не означает «нет в наличии» у старых товаров.', null=True, verbose_name='Остаток'),
        ),
        migrations.AddField(
            model_name='productimage',
            name='is_primary',
            field=models.BooleanField(default=False, help_text='Не заменяет главное фото товара (main_image).', verbose_name='Основное в галерее'),
        ),
        migrations.AddField(
            model_name='productimage',
            name='sort_order',
            field=models.PositiveIntegerField(default=0, verbose_name='Порядок'),
        ),
        migrations.AddConstraint(
            model_name='product',
            constraint=models.UniqueConstraint(condition=models.Q(('seller_profile__isnull', False), models.Q(('article', ''), _negated=True)), fields=('seller_profile', 'article'), name='uniq_prod_article_per_seller'),
        ),
        migrations.AddConstraint(
            model_name='product',
            constraint=models.CheckConstraint(condition=models.Q(('stock_qty__isnull', True), ('stock_qty__gte', 0), _connector='OR'), name='catalog_product_stock_qty_gte_0'),
        ),
        migrations.AddConstraint(
            model_name='product',
            constraint=models.CheckConstraint(condition=models.Q(('cost_price__isnull', True), ('cost_price__gte', 0), _connector='OR'), name='catalog_product_cost_price_gte_0'),
        ),
        migrations.AddField(
            model_name='productconsignment',
            name='product',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='consignment', to='catalog.product', verbose_name='Товар'),
        ),
        migrations.AddField(
            model_name='productpricetier',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='price_tiers', to='catalog.product', verbose_name='Товар'),
        ),
        migrations.AddField(
            model_name='productpromotion',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='promotions', to='catalog.product', verbose_name='Товар'),
        ),
        migrations.AddConstraint(
            model_name='productconsignment',
            constraint=models.CheckConstraint(condition=models.Q(('max_qty__gte', 0)), name='product_consignment_max_qty_gte_0'),
        ),
        migrations.AddConstraint(
            model_name='productconsignment',
            constraint=models.CheckConstraint(condition=models.Q(('settlement_price__gte', 0)), name='product_consignment_price_gte_0'),
        ),
        migrations.AddConstraint(
            model_name='productconsignment',
            constraint=models.CheckConstraint(condition=models.Q(('term_days__gte', 0)), name='product_consignment_term_days_gte_0'),
        ),
        migrations.AddConstraint(
            model_name='productpricetier',
            constraint=models.UniqueConstraint(fields=('product', 'min_qty'), name='unique_product_price_tier_min_qty'),
        ),
        migrations.AddConstraint(
            model_name='productpricetier',
            constraint=models.CheckConstraint(condition=models.Q(('min_qty__gt', 0)), name='product_price_tier_min_qty_gt_0'),
        ),
        migrations.AddConstraint(
            model_name='productpricetier',
            constraint=models.CheckConstraint(condition=models.Q(('price__gte', 0)), name='product_price_tier_price_gte_0'),
        ),
        migrations.AddConstraint(
            model_name='productpromotion',
            constraint=models.CheckConstraint(condition=models.Q(('price__gte', 0)), name='product_promotion_price_gte_0'),
        ),
        migrations.AddConstraint(
            model_name='productpromotion',
            constraint=models.CheckConstraint(condition=models.Q(('qty_limit__isnull', True), ('qty_limit__gte', 0), _connector='OR'), name='product_promotion_qty_limit_gte_0'),
        ),
    ]
