# Generated by Django 6.0.5 on 2026-08-25 04:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0017_product_commercial_terms'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductConsignmentRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requested_qty', models.PositiveIntegerField(verbose_name='Запрошенное количество')),
                ('status', models.CharField(choices=[('new', 'Новая'), ('approved', 'Одобрена'), ('rejected', 'Отклонена'), ('issued', 'Выдана'), ('closed', 'Закрыта'), ('cancelled', 'Отменена')], default='new', max_length=16, verbose_name='Статус')),
                ('settlement_price', models.PositiveIntegerField(help_text='Снимок условий. Позднее изменение реализации товар не меняет эту заявку.', verbose_name='Расчётная цена на момент заявки, ₸')),
                ('term_days', models.PositiveIntegerField(default=0, verbose_name='Срок реализации, дней')),
                ('conditions', models.TextField(blank=True, default='', verbose_name='Условия на момент заявки')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='consignment_requests', to='catalog.product', verbose_name='Товар')),
                ('seller_profile', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='consignment_requests', to='catalog.sellerprofile', verbose_name='Продавец')),
            ],
            options={
                'verbose_name': 'Заявка на реализацию',
                'verbose_name_plural': 'Заявки на реализацию',
                'ordering': ['-created_at'],
            },
        ),
    ]
