# Generated by Django 6.0.5 on 2026-08-26 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0018_productconsignmentrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='engine_compatibility',
            field=models.TextField(blank=True, default='', help_text='Применяемость по двигателям. По одному значению на строку или через точку с запятой. Без HTML.', verbose_name='Двигатели'),
        ),
        migrations.AddField(
            model_name='product',
            name='oem_cross_references',
            field=models.TextField(blank=True, default='', help_text='OEM и кросс-номера. По одному значению на строку или через точку с запятой. Без HTML и ссылок.', verbose_name='OEM / кросс-номера'),
        ),
    ]
