# Generated by Django 6.0.5 on 2026-08-26 11:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0019_product_engine_oem_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='publish_to_kaspi',
            field=models.BooleanField(default=False, help_text='Мастер-разрешение для Kaspi. Реальная публикация карточки: Product.publish_to_kaspi AND listing.publish_to_kaspi AND listing.is_active. Importer не меняет этот флаг.', verbose_name='Разрешить публикацию в Kaspi'),
        ),
        migrations.AddField(
            model_name='product',
            name='publish_to_sellers',
            field=models.BooleanField(default=False, help_text='Разрешает товар в коммерческих рассылках продавцам. Не зависит от status. Importer не меняет этот флаг.', verbose_name='Публиковать продавцам'),
        ),
        migrations.CreateModel(
            name='CatalogImportBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(db_index=True, default='ag_parts', max_length=64, verbose_name='Источник')),
                ('filename', models.CharField(max_length=255, verbose_name='Имя файла')),
                ('file_sha256', models.CharField(db_index=True, max_length=64, verbose_name='SHA256 источника')),
                ('source_archive_path', models.CharField(blank=True, default='', max_length=500, verbose_name='Путь архива источника')),
                ('archive_status', models.CharField(choices=[('not_applicable', 'Не применимо'), ('success', 'Архив сохранён'), ('error', 'Ошибка архива')], db_index=True, default='not_applicable', max_length=16, verbose_name='Статус архива')),
                ('archive_error', models.TextField(blank=True, default='', verbose_name='Ошибка архива')),
                ('started_at', models.DateTimeField(verbose_name='Начало')),
                ('finished_at', models.DateTimeField(blank=True, null=True, verbose_name='Окончание')),
                ('mode', models.CharField(choices=[('write', 'Write'), ('dry-run', 'Dry-run')], default='write', max_length=16, verbose_name='Режим')),
                ('source_scope', models.CharField(choices=[('full', 'Полный каталог'), ('partial', 'Частичный импорт')], db_index=True, default='partial', max_length=16, verbose_name='Охват источника')),
                ('status', models.CharField(choices=[('success', 'Успех'), ('blocked', 'Блок (shrink guard)'), ('error', 'Ошибка')], db_index=True, default='success', max_length=16, verbose_name='Статус')),
                ('source_row_count', models.PositiveIntegerField(default=0, verbose_name='Строк в источнике')),
                ('source_unique_count', models.PositiveIntegerField(default=0, verbose_name='Уникальных в источнике')),
                ('selected_count', models.PositiveIntegerField(default=0, verbose_name='Выбрано после фильтра')),
                ('created_count', models.PositiveIntegerField(default=0)),
                ('updated_count', models.PositiveIntegerField(default=0)),
                ('unchanged_count', models.PositiveIntegerField(default=0)),
                ('skipped_count', models.PositiveIntegerField(default=0)),
                ('conflict_count', models.PositiveIntegerField(default=0)),
                ('warning_count', models.PositiveIntegerField(default=0)),
                ('error_count', models.PositiveIntegerField(default=0)),
                ('missing_from_source_count', models.PositiveIntegerField(default=0)),
                ('blocked_reason', models.TextField(blank=True, default='', verbose_name='Причина блока')),
                ('allow_source_shrink_reason', models.TextField(blank=True, default='', verbose_name='Причина обхода shrink guard')),
                ('previous_successful_batch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='following_batches', to='catalog.catalogimportbatch', verbose_name='Предыдущий успешный full write')),
                ('seller_profile', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='catalog_import_batches', to='catalog.sellerprofile', verbose_name='Профиль продавца')),
            ],
            options={
                'verbose_name': 'Пакет импорта каталога',
                'verbose_name_plural': 'Пакеты импорта каталога',
                'ordering': ['-started_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='CatalogImportItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('article', models.CharField(db_index=True, max_length=100, verbose_name='Артикул')),
                ('action', models.CharField(choices=[('created', 'Created'), ('updated', 'Updated'), ('unchanged', 'Unchanged'), ('skipped', 'Skipped'), ('conflict', 'Conflict'), ('error', 'Error'), ('missing_from_source', 'Missing from source')], max_length=32, verbose_name='Действие')),
                ('warnings', models.JSONField(blank=True, default=list, verbose_name='Предупреждения')),
                ('errors', models.JSONField(blank=True, default=list, verbose_name='Ошибки')),
                ('changed_fields', models.JSONField(blank=True, default=dict, verbose_name='Изменённые поля')),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='catalog.catalogimportbatch', verbose_name='Пакет')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='catalog_import_items', to='catalog.product', verbose_name='Товар')),
            ],
            options={
                'verbose_name': 'Строка импорта каталога',
                'verbose_name_plural': 'Строки импорта каталога',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='ProductBarcode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(db_index=True, max_length=64, verbose_name='Штрихкод')),
                ('source', models.CharField(choices=[('wms', 'WMS'), ('kaspi', 'Kaspi'), ('manual', 'Вручную')], default='wms', max_length=16, verbose_name='Источник')),
                ('is_primary', models.BooleanField(default=False, verbose_name='Основной')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='barcodes', to='catalog.product', verbose_name='Товар')),
            ],
            options={
                'verbose_name': 'Штрихкод товара',
                'verbose_name_plural': 'Штрихкоды товаров',
                'ordering': ['-is_primary', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ProductFulfillment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.CharField(blank=True, default='', help_text='Внешний идентификатор склада. Не заполнять автоматически из артикула: в текущем WMS Excel отдельного надёжного Fulfillment ID нет.', max_length=128, verbose_name='Fulfillment / WMS ID')),
                ('source', models.CharField(choices=[('wms', 'WMS'), ('manual', 'Вручную')], default='wms', max_length=32, verbose_name='Источник')),
                ('last_synced_at', models.DateTimeField(blank=True, null=True, verbose_name='Последняя синхронизация')),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='fulfillment', to='catalog.product', verbose_name='Товар')),
            ],
            options={
                'verbose_name': 'Fulfillment-идентификатор',
                'verbose_name_plural': 'Fulfillment-идентификаторы',
            },
        ),
        migrations.CreateModel(
            name='ProductKaspiListing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('master_sku', models.CharField(db_index=True, help_text='Идентификатор карточки Kaspi (колонка SKU в выгрузке).', max_length=128, verbose_name='Kaspi master SKU')),
                ('merchant_sku', models.CharField(blank=True, db_index=True, default='', help_text='Артикул продавца в Kaspi. Не путать с master_sku.', max_length=128, verbose_name='Kaspi merchant SKU')),
                ('barcode', models.CharField(blank=True, default='', max_length=64, verbose_name='Штрихкод Kaspi')),
                ('is_active', models.BooleanField(default=True, verbose_name='Листинг активен')),
                ('publish_to_kaspi', models.BooleanField(default=False, verbose_name='Публиковать этот листинг в Kaspi')),
                ('last_known_our_price', models.PositiveIntegerField(blank=True, null=True, verbose_name='Последняя наша цена в Kaspi')),
                ('last_synced_at', models.DateTimeField(blank=True, null=True, verbose_name='Последняя синхронизация')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kaspi_listings', to='catalog.product', verbose_name='Товар')),
            ],
            options={
                'verbose_name': 'Kaspi-листинг',
                'verbose_name_plural': 'Kaspi-листинги',
                'ordering': ['id'],
            },
        ),
        migrations.AddIndex(
            model_name='catalogimportbatch',
            index=models.Index(fields=['seller_profile', 'source', 'source_scope', 'mode', 'status'], name='cat_import_batch_lookup_idx'),
        ),
        migrations.AddIndex(
            model_name='catalogimportitem',
            index=models.Index(fields=['batch', 'action'], name='cat_import_item_action_idx'),
        ),
        migrations.AddIndex(
            model_name='catalogimportitem',
            index=models.Index(fields=['article'], name='cat_import_item_article_idx'),
        ),
        migrations.AddIndex(
            model_name='productbarcode',
            index=models.Index(fields=['code'], name='cat_barcode_code_idx'),
        ),
        migrations.AddConstraint(
            model_name='productbarcode',
            constraint=models.UniqueConstraint(fields=('product', 'code'), name='uniq_product_barcode_code'),
        ),
        migrations.AddIndex(
            model_name='productkaspilisting',
            index=models.Index(fields=['product', 'is_active'], name='cat_kaspi_listing_active_idx'),
        ),
        migrations.AddConstraint(
            model_name='productkaspilisting',
            constraint=models.UniqueConstraint(fields=('product', 'master_sku'), name='uniq_product_kaspi_master_sku'),
        ),
    ]
