# Generated by Django 6.0.5 on 2026-09-15 04:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0030_warehouse_stock'),
    ]

    operations = [
        migrations.AddField(
            model_name='productkaspilisting',
            name='last_known_kaspi_qty',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Последний наблюдаемый остаток Kaspi'),
        ),
        migrations.CreateModel(
            name='KaspiListingFactSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('observed_price', models.PositiveIntegerField(blank=True, null=True, verbose_name='Наблюдаемая цена Kaspi')),
                ('observed_qty', models.PositiveIntegerField(blank=True, null=True, verbose_name='Наблюдаемый остаток Kaspi')),
                ('source', models.CharField(choices=[('active_xlsx', 'Kaspi active.xlsx'), ('manual_import', 'Ручной импорт')], db_index=True, default='active_xlsx', max_length=32, verbose_name='Источник')),
                ('source_filename', models.CharField(default='', max_length=255, verbose_name='Имя файла')),
                ('source_sha256', models.CharField(db_index=True, max_length=64, verbose_name='SHA256 источника')),
                ('source_row', models.PositiveIntegerField(blank=True, null=True, verbose_name='Строка источника')),
                ('observed_at', models.DateTimeField(verbose_name='Наблюдено')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('import_batch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='kaspi_listing_fact_snapshots', to='catalog.catalogimportbatch', verbose_name='Пакет импорта')),
                ('listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fact_snapshots', to='catalog.productkaspilisting', verbose_name='Kaspi-листинг')),
            ],
            options={
                'verbose_name': 'Снимок факта Kaspi',
                'verbose_name_plural': 'Снимки фактов Kaspi',
                'ordering': ['-observed_at', '-id'],
                'indexes': [models.Index(fields=['listing', 'observed_at'], name='cat_kaspi_fact_list_obs_idx')],
                'constraints': [models.UniqueConstraint(fields=('listing', 'source_sha256'), name='uniq_kaspi_fact_listing_source')],
            },
        ),
    ]
