# Generated by Django 6.0.5 on 2026-09-15 06:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0031_kaspi_listing_facts'),
    ]

    operations = [
        migrations.CreateModel(
            name='KaspiOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_order_id', models.CharField(db_index=True, max_length=128, verbose_name='Номер заказа Kaspi (ID/RRN)')),
                ('first_operation_at', models.DateTimeField(blank=True, null=True, verbose_name='Первая операция')),
                ('last_operation_at', models.DateTimeField(blank=True, null=True, verbose_name='Последняя операция')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('seller_profile', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='kaspi_orders', to='catalog.sellerprofile', verbose_name='Профиль продавца')),
            ],
            options={
                'verbose_name': 'Заказ Kaspi',
                'verbose_name_plural': 'Заказы Kaspi',
                'ordering': ['-last_operation_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='KaspiSalesOperation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purchase_return_document', models.CharField(blank=True, default='', max_length=128, verbose_name='№ документа Покупки/Возврата')),
                ('sales_point_id', models.CharField(blank=True, default='', max_length=64, verbose_name='Идентификатор точки')),
                ('terminal_id', models.CharField(blank=True, default='', max_length=64, verbose_name='ID терминала')),
                ('operation_type', models.CharField(choices=[('PURCHASE', 'Покупка'), ('RETURN', 'Возврат')], db_index=True, max_length=16, verbose_name='Тип операции')),
                ('operation_at', models.DateTimeField(db_index=True, verbose_name='Дата/время операции')),
                ('accounting_date', models.DateField(blank=True, null=True, verbose_name='Дата учета операции')),
                ('payment_type', models.CharField(blank=True, default='', max_length=64, verbose_name='Тип оплаты')),
                ('payment_type_2', models.CharField(blank=True, default='', max_length=64, verbose_name='Тип оплаты 2')),
                ('gross_amount', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='Сумма операции')),
                ('settlement_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True, verbose_name='Сумма к зачислению/списанию')),
                ('commission_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True, verbose_name='Комиссия за операции')),
                ('commission_ex_vat_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True, verbose_name='Комиссия за операции без НДС')),
                ('commission_ex_vat_percent', models.DecimalField(blank=True, decimal_places=4, max_digits=8, null=True, verbose_name='Комиссия за операции % без НДС')),
                ('card_commission_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True, verbose_name='Комиссия за операции по карте')),
                ('card_commission_percent', models.DecimalField(blank=True, decimal_places=4, max_digits=8, null=True, verbose_name='Комиссия за операции по карте %')),
                ('payment_guarantee_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True, verbose_name='Комиссия за обеспечение платежа')),
                ('payment_guarantee_percent', models.DecimalField(blank=True, decimal_places=4, max_digits=8, null=True, verbose_name='Комиссия за обеспечение платежа %')),
                ('kaspi_pay_commission_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True, verbose_name='Комиссия Kaspi Pay')),
                ('kaspi_pay_commission_percent', models.DecimalField(blank=True, decimal_places=4, max_digits=8, null=True, verbose_name='Комиссия Kaspi Pay %')),
                ('kaspi_travel_commission_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True, verbose_name='Комиссия Kaspi Travel')),
                ('kaspi_travel_commission_percent', models.DecimalField(blank=True, decimal_places=4, max_digits=8, null=True, verbose_name='Комиссия Kaspi Travel %')),
                ('bonus_product_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True, verbose_name='Бонусы на товар')),
                ('bonus_review_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True, verbose_name='Бонусы за отзыв')),
                ('delivery_document', models.CharField(blank=True, default='', max_length=128, verbose_name='№ документа Kaspi Доставка')),
                ('delivery_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True, verbose_name='Стоимость Kaspi Доставки')),
                ('installment_term', models.CharField(blank=True, default='', max_length=64, verbose_name='Срок кредита на покупки')),
                ('details', models.TextField(blank=True, default='', verbose_name='Детали покупки')),
                ('quantity', models.PositiveIntegerField(verbose_name='Количество')),
                ('unit_gross_amount', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='Сумма за единицу')),
                ('match_status', models.CharField(choices=[('LISTING_MATCHED', 'Listing'), ('PRODUCT_ONLY', 'Только товар'), ('UNMATCHED', 'Не найден'), ('AMBIGUOUS_PRODUCT', 'Несколько товаров')], db_index=True, max_length=24, verbose_name='Статус сопоставления')),
                ('matched_identifier', models.CharField(blank=True, default='', max_length=128, verbose_name='Сопоставленный идентификатор')),
                ('source_filename', models.CharField(default='', max_length=255, verbose_name='Имя файла')),
                ('source_sha256', models.CharField(db_index=True, max_length=64, verbose_name='SHA256 источника')),
                ('source_row', models.PositiveIntegerField(blank=True, null=True, verbose_name='Строка источника')),
                ('source_fingerprint', models.CharField(db_index=True, max_length=64, verbose_name='Отпечаток операции')),
                ('raw_data', models.JSONField(blank=True, default=dict, verbose_name='Сырые данные строки')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('import_batch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='kaspi_sales_operations', to='catalog.catalogimportbatch', verbose_name='Пакет импорта')),
                ('listing', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='kaspi_sales_operations', to='catalog.productkaspilisting', verbose_name='Kaspi-листинг')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='operations', to='catalog.kaspiorder', verbose_name='Заказ Kaspi')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='kaspi_sales_operations', to='catalog.product', verbose_name='Товар')),
                ('seller_profile', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='kaspi_sales_operations', to='catalog.sellerprofile', verbose_name='Профиль продавца')),
            ],
            options={
                'verbose_name': 'Операция продаж Kaspi',
                'verbose_name_plural': 'Операции продаж Kaspi',
                'ordering': ['-operation_at', '-id'],
            },
        ),
        migrations.AddConstraint(
            model_name='kaspiorder',
            constraint=models.UniqueConstraint(fields=('seller_profile', 'external_order_id'), name='uniq_kaspi_order_seller_external'),
        ),
        migrations.AddIndex(
            model_name='kaspisalesoperation',
            index=models.Index(fields=['seller_profile', 'operation_type', 'operation_at'], name='cat_kaspi_sales_seller_op_idx'),
        ),
        migrations.AddConstraint(
            model_name='kaspisalesoperation',
            constraint=models.UniqueConstraint(fields=('seller_profile', 'source_fingerprint'), name='uniq_kaspi_sales_seller_fingerprint'),
        ),
    ]
