# Generated by Django 6.0.5 on 2026-09-15 09:44

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0032_kaspi_sales_report'),
    ]

    operations = [
        migrations.CreateModel(
            name='KaspiEconomicsConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fulfillment_packaging_per_unit', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Упаковка Fulfillment за единицу')),
                ('fulfillment_handling_per_unit', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Обработка Fulfillment за единицу')),
                ('default_min_margin_percent', models.DecimalField(decimal_places=4, help_text='Человеческий процент: 15.00 = 15%. Не доля.', max_digits=8, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Мин. маржа по умолчанию, %')),
                ('is_active', models.BooleanField(default=True, verbose_name='Конфиг активен')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('seller_profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='kaspi_economics_config', to='catalog.sellerprofile', verbose_name='Профиль продавца')),
            ],
            options={
                'verbose_name': 'Конфиг экономики Kaspi',
                'verbose_name_plural': 'Конфиги экономики Kaspi',
                'constraints': [models.CheckConstraint(condition=models.Q(('fulfillment_packaging_per_unit__gte', 0)), name='kaspi_econ_packaging_gte_0'), models.CheckConstraint(condition=models.Q(('fulfillment_handling_per_unit__gte', 0)), name='kaspi_econ_handling_gte_0'), models.CheckConstraint(condition=models.Q(('default_min_margin_percent__gte', 0)), name='kaspi_econ_margin_gte_0')],
            },
        ),
        migrations.CreateModel(
            name='ProductKaspiEconomicsPolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min_margin_percent', models.DecimalField(blank=True, decimal_places=4, help_text='Пусто = взять default_min_margin_percent продавца. 15.00 = 15%.', max_digits=8, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Мин. маржа товара, %')),
                ('manual_min_price', models.DecimalField(blank=True, decimal_places=2, help_text='Не снижает расчётный floor, только поднимает его.', max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Ручной минимальный floor')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='kaspi_economics_policy', to='catalog.product', verbose_name='Товар')),
            ],
            options={
                'verbose_name': 'Политика экономики товара Kaspi',
                'verbose_name_plural': 'Политики экономики товаров Kaspi',
                'constraints': [models.CheckConstraint(condition=models.Q(('min_margin_percent__isnull', True), ('min_margin_percent__gte', 0), _connector='OR'), name='kaspi_econ_policy_margin_gte_0'), models.CheckConstraint(condition=models.Q(('manual_min_price__isnull', True), ('manual_min_price__gte', 0), _connector='OR'), name='kaspi_econ_policy_manual_gte_0')],
            },
        ),
    ]
