# Generated by Django 6.0.5 on 2026-09-16 05:14

import catalog.kaspi_public_url
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0033_kaspi_economics'),
    ]

    operations = [
        migrations.AddField(
            model_name='productkaspilisting',
            name='public_url',
            field=models.URLField(blank=True, default='', help_text='Проверенная публичная ссылка на карточку товара в Магазине Kaspi. Не формируется автоматически из master_sku.', max_length=500, validators=[catalog.kaspi_public_url.validate_kaspi_public_url], verbose_name='Публичная ссылка Kaspi'),
        ),
    ]
