# Generated by Django 6.0.5 on 2026-09-21 07:43

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0034_kaspi_listing_public_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='MaintenanceKit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('slug', models.SlugField(max_length=255, unique=True, validators=[django.core.validators.RegexValidator(message='Slug может содержать только латиницу, цифры и дефис.', regex='^[a-z0-9]+(?:-[a-z0-9]+)*$')], verbose_name='URL')),
                ('engine', models.CharField(blank=True, default='', max_length=80, verbose_name='Двигатель')),
                ('year_from', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Год от')),
                ('year_to', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Год до')),
                ('description', models.TextField(blank=True, default='', verbose_name='Описание')),
                ('is_active', models.BooleanField(db_index=True, default=False, verbose_name='Опубликован')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='maintenance_kits', to='catalog.brand', verbose_name='Марка')),
                ('car_model', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='maintenance_kits', to='catalog.carmodel', verbose_name='Модель')),
            ],
            options={
                'verbose_name': 'Комплект ТО',
                'verbose_name_plural': 'Комплекты ТО',
                'ordering': ['brand__name', 'car_model__name', 'name'],
            },
        ),
        migrations.CreateModel(
            name='MaintenanceKitItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Количество')),
                ('kit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='catalog.maintenancekit', verbose_name='Комплект')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='maintenance_kit_items', to='catalog.product', verbose_name='Товар')),
            ],
            options={
                'verbose_name': 'Позиция комплекта ТО',
                'verbose_name_plural': 'Позиции комплектов ТО',
                'ordering': ['id'],
                'constraints': [models.UniqueConstraint(fields=('kit', 'product'), name='uniq_maintenance_kit_item_product'), models.CheckConstraint(condition=models.Q(('quantity__gte', 1)), name='maintenance_kit_item_qty_gte_1')],
            },
        ),
    ]
