# Generated by Django 6.0.5 on 2026-09-24 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0037_maintenance_kit_car_request'),
    ]

    operations = [
        migrations.AddField(
            model_name='maintenancekitcarrequest',
            name='phone',
            field=models.CharField(blank=True, default='', help_text='Пусто у заявок, оставленных до появления поля. Новые заявки сохраняют номер.', max_length=20, verbose_name='Телефон / WhatsApp'),
        ),
        migrations.AddField(
            model_name='maintenancekitcarrequest',
            name='status',
            field=models.CharField(choices=[('new', 'Новая'), ('in_progress', 'В работе'), ('closed', 'Закрыта')], db_index=True, default='new', max_length=20, verbose_name='Статус'),
        ),
        migrations.AddIndex(
            model_name='maintenancekitcarrequest',
            index=models.Index(fields=['status', '-created_at'], name='kit_car_req_status_created_idx'),
        ),
    ]
