# Generated by Django 6.0.5 on 2026-06-30 07:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0011_sellerprofile_b2b_contacts'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=255, verbose_name='Имя покупателя')),
                ('customer_phone', models.CharField(max_length=30, verbose_name='Телефон')),
                ('status', models.CharField(choices=[('new', 'Новый / Создан'), ('pending_payment', 'Ожидает оплаты Kaspi'), ('paid', 'Оплачен / Передан на сборку поставщику'), ('canceled', 'Отменен')], default='new', max_length=20, verbose_name='Статус')),
                ('total_price', models.PositiveIntegerField(verbose_name='Сумма заказа, ₸')),
                ('delivery_method', models.CharField(choices=[('pickup', 'Самовывоз'), ('courier', 'Курьер по городу'), ('kz_delivery', 'Доставка по Казахстану')], max_length=20, verbose_name='Способ доставки')),
                ('delivery_address', models.JSONField(blank=True, default=dict, verbose_name='Данные доставки')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлен')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Заказ',
                'verbose_name_plural': 'Заказы',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='KaspiTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kaspi_id', models.CharField(blank=True, default='', max_length=128, verbose_name='ID транзакции Kaspi')),
                ('status', models.CharField(max_length=64, verbose_name='Статус')),
                ('raw_response', models.JSONField(blank=True, default=dict, verbose_name='Ответ банка')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kaspi_transactions', to='orders.order', verbose_name='Заказ')),
            ],
            options={
                'verbose_name': 'Транзакция Kaspi',
                'verbose_name_plural': 'Транзакции Kaspi',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='Количество')),
                ('price_at_purchase', models.PositiveIntegerField(verbose_name='Цена на момент покупки, ₸')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='orders.order', verbose_name='Заказ')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='order_items', to='catalog.product', verbose_name='Товар')),
            ],
            options={
                'verbose_name': 'Позиция заказа',
                'verbose_name_plural': 'Позиции заказа',
            },
        ),
    ]
