# Generated by Django 6.0.5 on 2026-08-28 07:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0024_catalogimportbatch_wholesale_update_audit'),
        ('orders', '0005_order_wholesale_terms_snapshot'),
    ]

    operations = [
        migrations.CreateModel(
            name='WholesaleFunnelEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('storefront_view', 'Витрина'), ('product_view', 'Карточка товара'), ('price_download', 'Скачивание прайса'), ('add_to_cart', 'Добавление в корзину'), ('checkout_view', 'Оформление'), ('order_created', 'Заказ')], db_index=True, max_length=32, verbose_name='Тип события')),
                ('visitor_id', models.UUIDField(db_index=True, verbose_name='Посетитель')),
                ('utm_source', models.CharField(blank=True, default='', max_length=100, verbose_name='UTM source')),
                ('utm_medium', models.CharField(blank=True, default='', max_length=100, verbose_name='UTM medium')),
                ('utm_campaign', models.CharField(blank=True, default='', max_length=150, verbose_name='UTM campaign')),
                ('quantity', models.PositiveIntegerField(blank=True, null=True, verbose_name='Количество')),
                ('value_kzt', models.PositiveIntegerField(blank=True, null=True, verbose_name='Сумма, ₸')),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='Метаданные')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Создано')),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='wholesale_funnel_events', to='orders.order', verbose_name='Заказ')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='wholesale_funnel_events', to='catalog.product', verbose_name='Товар')),
                ('seller_profile', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='wholesale_funnel_events', to='catalog.sellerprofile', verbose_name='Продавец')),
            ],
            options={
                'verbose_name': 'Событие оптовой воронки',
                'verbose_name_plural': 'События оптовой воронки',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['seller_profile', 'event_type', 'created_at'], name='wh_funnel_seller_evt_idx'), models.Index(fields=['utm_campaign', 'created_at'], name='wh_funnel_campaign_idx'), models.Index(fields=['visitor_id', 'event_type', 'created_at'], name='wh_funnel_visitor_evt_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('event_type', 'order_created')), fields=('order',), name='uniq_wholesale_funnel_order_created')],
            },
        ),
    ]
