# Generated by Django 6.0.5 on 2026-10-07 04:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0057_sync_three_kaspi_prices_20261002'),
        ('orders', '0006_wholesalefunnelevent'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='seller_profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='merchant_orders', to='catalog.sellerprofile', verbose_name='Профиль продавца'),
        ),
    ]
